# -*- coding: utf-8 -*-
"""GNN_GraphSage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R_jrZp5ygwTdrgnTKGcK7MIwNQ8-xHsx

# Student Profile Analysis and Recommendation

This notebook demonstrates a process for analyzing student profiles and generating friend recommendations based on their characteristics and interests.

## 1. Data Loading and Initial Inspection

This section loads the student profile data from a CSV file and performs an initial inspection of the data, including viewing the first few rows and checking data types and missing values.
"""

# Import the pandas library, the cornerstone for data analysis in Python
import pandas as pd

df = pd.read_csv('profiles_processed.csv')

print("First 5 rows of the dataset:")
print(df.head())
print("\nDataset Information:")
df.info()

# Get unique values for Major and Year
unique_majors = df['Major'].unique()
unique_years = df['Year'].unique()

print("Unique Majors:")
print(unique_majors)
print("\nUnique Years:")
print(unique_years)

course_catalog = {
    'Accounting': ['ACTG 210: Intro to Financial Accounting', 'ACTG 211: Intro to Managerial Accounting', 'ACTG 315: Intermediate Financial Accounting I', 'ACTG 316: Intermediate Financial Accounting II', 'ACTG 326: Cost Accounting', 'ACTG 435: Auditing', 'ACTG 445: Federal Income Tax I', 'IDS 270: Business Statistics I'],
    'Aerospace Engineering': ['ME 210: Engineering Dynamics', 'ME 211: Fluid Mechanics I', 'ME 308: Mechanical Vibrations', 'ME 312: Dynamic Systems and Control', 'ME 321: Heat Transfer', 'ME 428: Aerodynamics', 'ME 429: Internal Combustion Engines', 'CME 203: Strength of Materials'],
    'Anthropology': ['ANTH 101: World Cultures: Intro to Social Anthro', 'ANTH 102: Intro to Archaeology', 'ANTH 105: Human Evolution', 'ANTH 213: Lab Methods in Archaeology', 'ANTH 309: Writing Culture', 'ANTH 411: Urban Cultural Problems', 'GEOG 151: Cultural Geography', 'SOC 225: Racial and Ethnic Groups'],
    'Archaeology': ['ANTH 102: Intro to Archaeology', 'ANTH 200: Archaeological Field Techniques', 'ANTH 202: Archaeological Laboratory Analysis', 'ANTH 329: Archaeological Theory', 'ANTH 420: Seminar in Archaeology', 'ANTH 426: Ancient Civilizations', 'GEOG 475: Thematic Cartography', 'HIST 202: Ancient Greece'],
    'Architecture': ['ARCH 105: Introduction to Architecture', 'ARCH 106: Architecture Design I', 'ARCH 200: Architectural Theory', 'ARCH 251: Architectural Analysis', 'ARCH 359: Architecture Structure I', 'ARCH 360: Architecture Structure II', 'ARCH 440: Digital Design and Fabrication', 'AH 110: World History of Art and Architecture'],
    'Art History': ['AH 100: Introduction to Art and Art History', 'AH 110: World History of Art I', 'AH 111: World History of Art II', 'AH 204: Greek Art and Archaeology', 'AH 205: Roman Art and Archaeology', 'AH 219: Art of the Renaissance', 'AH 260: European Art 1750-1900', 'AH 263: Latin American Art'],
    'Art Therapy': ['PSCH 100: Intro to Psychology', 'ART 110: Drawing I', 'ART 150: Intro to Painting', 'PSCH 270: Abnormal Psychology', 'PSCH 312: Introduction to Clinical Psychology', 'AH 111: World History of Art', 'ART 210: Drawing II', 'PSCH 385: Developmental Psychology'],
    'Biochemistry': ['BIOS 110: Biology of Cells and Organisms', 'CHEM 122: General Chemistry I', 'CHEM 232: Organic Chemistry I', 'CHEM 352: Introductory Biochemistry', 'CHEM 452: Biochemistry I', 'CHEM 454: Biochemistry II', 'BIOS 220: Genetics', 'PHYS 141: General Physics I'],
    'Biology': ['BIOS 110: Biology of Cells and Organisms', 'BIOS 120: Biology of Populations and Communities', 'BIOS 220: Genetics', 'BIOS 222: Cell Biology', 'BIOS 230: Evolution and Ecology', 'BIOS 310: Genetics Laboratory', 'BIOS 325: Human Embryology', 'BIOS 350: General Microbiology'],
    'Biomedical Engineering': ['BME 101: Intro to Biomedical Engineering', 'BME 240: Modeling Physiological Data', 'BME 250: Clinical Problems in BME', 'BME 310: Biological Systems Analysis', 'BME 339: Biostatistics', 'BME 460: Neuromuscular Engineering', 'BIOS 443: Animal Physiological Systems', 'ECE 210: Electrical Circuit Analysis'],
    'Botany': ['BIOS 110: Biology of Cells and Organisms', 'BIOS 230: Evolution and Ecology', 'BIOS 305: Plant Evolutionary Ecology', 'BIOS 331: General Ecology', 'BIOS 430: Evolution', 'BIOS 431: Plant and Animal Interactions', 'EAES 101: Global Environmental Change', 'CHEM 232: Organic Chemistry I'],
    'Business Administration': ['ACTG 210: Intro to Financial Accounting', 'ECON 120: Principles of Microeconomics', 'FIN 300: Introduction to Finance', 'IDS 200: Intro to Management Info Systems', 'MGMT 340: Introduction to Organizations', 'MKTG 360: Introduction to Marketing', 'BA 200: Business Communications', 'IDS 355: Operations Management'],
    'Chemical Engineering': ['CHE 201: Intro to Thermodynamics', 'CHE 210: Material and Energy Balances', 'CHE 301: Chemical Engineering Thermodynamics', 'CHE 311: Transport Phenomena I', 'CHE 312: Transport Phenomena II', 'CHE 321: Chemical Reaction Engineering', 'CHE 410: Process Dynamics and Control', 'CHEM 232: Organic Chemistry I'],
    'Civil Engineering': ['CME 201: Statics', 'CME 203: Strength of Materials', 'CME 211: Fluid Mechanics and Hydraulics', 'CME 301: Behavior and Design of Metal Structures', 'CME 302: Transportation Engineering', 'CME 311: Water Resources Engineering', 'CME 315: Soil Mechanics', 'CME 402: Geometric Design of Highway Facilities'],
    'Classics': ['CL 100: Greek Civilization', 'CL 102: Roman Civilization', 'CL 201: Medical Terminology', 'CL 204: Greek Art and Archaeology', 'CL 205: Roman Art and Archaeology', 'CL 250: Greek Mythology', 'LARC 101: Beginning Latin I', 'HIST 202: Ancient Greece'],
    'Communication': ['COMM 101: Intro to Communication', 'COMM 102: Intro to Interpersonal Communication', 'COMM 103: Intro to Media', 'COMM 200: Communication Technologies', 'COMM 301: Communication Research', 'COMM 305: Media and Society', 'COMM 416: Conflict and Communication', 'COMM 433: Mass Media and Politics'],
    'Computer Engineering': ['CS 111: Program Design I', 'CS 141: Program Design II', 'CS 211: Programming Practicum', 'CS 251: Data Structures', 'ECE 115: Intro to Electrical & Computer Engineering', 'ECE 265: Intro to Logic Design', 'ECE 267: Computer Organization I', 'ECE 366: Computer Architecture'],
    'Computer Science': ['CS 111: Program Design I', 'CS 141: Program Design II', 'CS 211: Programming Practicum', 'CS 251: Data Structures', 'CS 261: Machine Organization', 'CS 341: Programming Languages', 'CS 342: Software Design', 'CS 401: Computer Algorithms'],
    'Criminology': ['CLJ 101: Intro to Criminology, Law, and Justice', 'CLJ 102: Foundations of Law and Justice', 'CLJ 200: Law and Society', 'CLJ 210: Principles of Criminal Law', 'CLJ 220: Criminology', 'CLJ 240: Criminal Justice Organizations', 'CLJ 261: Race, Class, and Justice', 'SOC 225: Racial and Ethnic Groups'],
    'Culinary Arts': ['HN 110: Foods and Nutrition', 'HN 202: Culture and Food', 'HN 300: Science of Foods', 'HN 302: Nutrition Education', 'MGMT 340: Intro to Organizations', 'MKTG 360: Intro to Marketing', 'CHEM 100: Chemistry and Life', 'BIOS 104: Biology for Non-Majors'],
    'Dance': ['THTR 111: Movement I', 'THTR 211: Movement II', 'THTR 219: Dance History', 'THTR 311: Movement IV: Style', 'MUS 100: Introduction to Music', 'KN 136: Principles of Exercise', 'THTR 101: Intro to Theatre', 'AH 111: World History of Art'],
    'Dentistry': ['BIOS 110: Biology of Cells and Organisms', 'BIOS 120: Biology of Populations', 'CHEM 122: General Chemistry I', 'CHEM 124: General Chemistry II', 'CHEM 232: Organic Chemistry I', 'CHEM 234: Organic Chemistry II', 'PHYS 141: General Physics I', 'BIOS 350: Microbiology'],
    'Drama': ['THTR 101: Intro to Theatre', 'THTR 141: Acting I', 'THTR 201: Modern Theatre', 'THTR 230: Script Analysis', 'THTR 241: Acting II', 'ENGL 104: Understanding Drama', 'ENGL 304: Studies in Drama', 'THTR 449: Senior Project'],
    'Early Childhood Education': ['ED 100: Intro to Urban Education', 'ED 205: Intro to Race and Ethnicity in Education', 'ED 257: Teaching English Learners', 'EPSY 255: Child Development', 'EPSY 326: Child Development in Context', 'SPED 410: Exceptional Learners', 'CI 405: Teaching Literacy', 'CI 406: Teaching Mathematics'],
    'Earth Science': ['EAES 101: Global Environmental Change', 'EAES 111: Earth, Energy, and Environment', 'EAES 200: Field Work in Earth Sciences', 'EAES 230: Earth Materials', 'EAES 285: Earth Systems', 'EAES 320: Mineralogy', 'EAES 440: Structural Geology', 'GEOG 100: Concepts in Geography'],
    'Ecology': ['BIOS 230: Evolution and Ecology', 'BIOS 331: General Ecology', 'BIOS 340: Environmental Physiology', 'BIOS 365: Human Ecological Systems', 'BIOS 430: Evolution', 'BIOS 431: Plant and Animal Interactions', 'EAES 101: Global Environmental Change', 'STAT 101: Intro to Statistics'],
    'Economics': ['ECON 120: Principles of Microeconomics', 'ECON 121: Principles of Macroeconomics', 'ECON 220: Microeconomics: Theory and Applications', 'ECON 221: Macroeconomics: Theory and Applications', 'ECON 270: Statistics for Economics', 'ECON 300: Econometrics', 'ECON 333: International Economics', 'MATH 180: Calculus I'],
    'Electrical Engineering': ['ECE 115: Intro to Electrical & Computer Engineering', 'ECE 210: Electrical Circuit Analysis', 'ECE 225: Circuit Analysis', 'ECE 310: Discrete and Continuous Signals', 'ECE 340: Electronics I', 'ECE 346: Solid State Device Theory', 'ECE 350: Principles of Automatic Control', 'MATH 220: Differential Equations'],
    'Elementary Education': ['ED 100: Intro to Urban Education', 'ED 210: The Educative Process', 'ED 258: Bilingualism and ESL', 'CI 401: Teaching Literacy', 'CI 402: Teaching Science', 'CI 403: Teaching Social Studies', 'CI 404: Teaching Mathematics', 'SPED 410: Exceptional Learners'],
    'English Literature': ['ENGL 101: Intro to Literature', 'ENGL 240: Intro to Literary Study', 'ENGL 241: English Literature I', 'ENGL 242: English Literature II', 'ENGL 243: American Literature', 'ENGL 311: Medieval Literature', 'ENGL 313: Renaissance Literature', 'ENGL 481: Methods of Teaching English'],
    'Environmental Science': ['EAES 101: Global Environmental Change', 'EAES 215: Intro to Environmental Sciences', 'EAES 320: Water Resources', 'EAES 475: Hydrology', 'BIOS 331: General Ecology', 'CHEM 122: General Chemistry I', 'US 130: Principles of Sustainability', 'GEOG 215: Geography of the Environment'],
    'Fashion Design': ['THTR 257: Costume Design I', 'THTR 258: Costume Design II', 'DES 140: Design Drawing', 'DES 170: Color Theory', 'AH 235: History of Design I', 'AH 236: History of Design II', 'MKTG 360: Intro to Marketing', 'ART 110: Drawing I'],
    'Film Studies': ['MOVI 131: Moving Image Arts', 'MOVI 132: History of Film I', 'MOVI 133: History of Film II', 'MOVI 200: Communication Technologies', 'MOVI 232: Documentary Film', 'ENGL 230: Intro to Film and Culture', 'AH 250: Art and Media', 'COMM 200: Communication Technologies'],
    'Forensic Science': ['CHEM 122: General Chemistry I', 'CHEM 222: Analytical Chemistry', 'CHEM 232: Organic Chemistry I', 'BIOS 220: Genetics', 'BIOS 222: Cell Biology', 'CLJ 101: Intro to Criminal Justice', 'CLJ 210: Principles of Criminal Law', 'CLJ 492: Forensic Science Internship'],
    'Geography': ['GEOG 100: Concepts in Geography', 'GEOG 151: Cultural Geography', 'GEOG 161: Intro to Economic Geography', 'GEOG 215: Geography of the Environment', 'GEOG 386: Urban Geography', 'GEOG 475: Thematic Cartography', 'GEOG 481: Geographic Information Systems I', 'EAES 101: Global Environmental Change'],
    'Geology': ['EAES 101: Global Environmental Change', 'EAES 111: Earth, Energy, Environment', 'EAES 230: Earth Materials', 'EAES 350: Sedimentology', 'EAES 360: Introduction to Paleontology', 'EAES 440: Structural Geology', 'EAES 444: Geophysics', 'CHEM 122: General Chemistry I'],
    'Graphic Communication': ['DES 120: 2D Form Studio', 'DES 150: Digital Media Design', 'DES 208: Typography I', 'DES 220: Form and Image Studio', 'COMM 200: Communication Technologies', 'COMM 301: Communication Research', 'MKTG 360: Intro to Marketing', 'DES 350: Mobile App Design'],
    'Graphic Design': ['DES 120: 2D Form Studio', 'DES 150: Digital Media Design', 'DES 208: Typography I', 'DES 209: Typography II', 'DES 220: Form and Image Studio', 'DES 308: Typography III', 'DES 410: Senior Design Colloquium', 'AH 235: History of Design I'],
    'Health Science': ['AHS 100: Intro to Health Sciences', 'AHS 200: Intro to Integrated Health Sciences', 'AHS 325: Approaches to Health Service', 'KN 251: Anatomy and Physiology', 'PUBH 100: Health and the Public', 'HN 196: Nutrition', 'PSCH 242: Intro to Research in Psychology', 'BIOS 110: Biology of Cells'],
    'History': ['HIST 100: Western Civilization to 1648', 'HIST 101: Western Civilization since 1648', 'HIST 103: US History to 1877', 'HIST 104: US History since 1877', 'HIST 300: History Methods', 'HIST 440: History Capstone', 'HIST 255: History of Chicago', 'HIST 272: China since 1911'],
    'Hospitality Management': ['MGMT 340: Intro to Organizations', 'MKTG 360: Intro to Marketing', 'HN 110: Foods and Nutrition', 'HN 202: Culture and Food', 'ACTG 210: Intro to Financial Accounting', 'COMM 102: Interpersonal Communication', 'ECON 120: Microeconomics', 'IDS 200: Intro to Management Information Systems'],
    'Industrial Design': ['DES 130: 3D Form Studio', 'DES 140: Design Drawing', 'DES 230: Industrial Design I', 'DES 231: Industrial Design II', 'DES 240: Visualization I', 'DES 330: Industrial Design III', 'DES 322: Design Research Methods', 'AH 236: History of Design II'],
    'Information Systems': ['IDS 200: Intro to Management Info Systems', 'IDS 201: Intro to Business Programming', 'IDS 270: Business Statistics I', 'IDS 312: Business Project Management', 'IDS 401: Business Object Programming', 'IDS 405: Business Systems Analysis', 'IDS 410: Business Database Technology', 'MGMT 340: Intro to Organizations'],
    'Interior Design': ['ARCH 105: Intro to Architecture', 'ARCH 106: Architecture Design I', 'DES 140: Design Drawing', 'DES 170: Color Theory', 'AH 235: History of Design I', 'ARCH 440: Digital Design', 'THTR 250: Scenic Design I', 'DES 222: Human Experience in Design'],
    'International Relations': ['POLS 130: Intro to Comparative Politics', 'POLS 184: Intro to International Relations', 'POLS 281: US Foreign Policy', 'POLS 283: International Political Economy', 'POLS 284: International Security', 'HIST 236: World History since 1450', 'ECON 333: International Economics', 'GEOG 151: Cultural Geography'],
    'Journalism': ['COMM 103: Intro to Media', 'COMM 200: Communication Technologies', 'COMM 216: Digital Journalism', 'COMM 301: Communication Research', 'COMM 335: Digital Storytelling', 'ENGL 202: Media and Professional Writing', 'POLS 101: Intro to American Politics', 'COMM 410: Media Law and Ethics'],
    'Kinesiology': ['KN 100: Kinesiology First Year Seminar', 'KN 136: Techniques of Exercise', 'KN 152: Intro to Exercise Physiology', 'KN 251: Human Anatomy and Physiology I', 'KN 252: Human Anatomy and Physiology II', 'KN 352: Physiology of Exercise', 'KN 361: Biomechanics', 'KN 396: Independent Study'],
    'Linguistics': ['LING 150: Intro to Language', 'LING 160: Language and Society', 'LING 220: Phonetics and Phonology', 'LING 210: Morphology and Syntax', 'LING 230: Semantics and Pragmatics', 'LING 300: Historical Linguistics', 'PSCH 366: Cognitive Neuroscience', 'LC 101: Intro to Cultural Studies'],
    'Management': ['MGMT 340: Intro to Organizations', 'MGMT 350: Business and its External Environment', 'MGMT 445: Organizational Theory', 'MGMT 452: Organizational Behavior', 'MGMT 453: Human Resource Management', 'MGMT 495: Competitive Strategy', 'IDS 355: Operations Management', 'MKTG 360: Intro to Marketing'],
    'Marine Biology': ['BIOS 110: Biology of Cells', 'BIOS 230: Evolution and Ecology', 'BIOS 331: General Ecology', 'BIOS 350: General Microbiology', 'EAES 101: Global Environmental Change', 'EAES 475: Hydrology', 'CHEM 232: Organic Chemistry I', 'BIOS 490: Topics in Ecology'],
    'Marketing': ['MKTG 360: Intro to Marketing', 'MKTG 370: Marketing Information Management', 'MKTG 461: Consumer Behavior', 'MKTG 462: Marketing Research', 'MKTG 465: Strategic Marketing Management', 'MKTG 474: Advertising and Promotion', 'COMM 103: Intro to Media', 'IDS 270: Business Statistics'],
    'Mathematics': ['MATH 180: Calculus I', 'MATH 181: Calculus II', 'MATH 210: Calculus III', 'MATH 215: Intro to Advanced Mathematics', 'MATH 310: Applied Linear Algebra', 'MATH 320: Linear Algebra I', 'MATH 330: Abstract Algebra I', 'MATH 410: Advanced Calculus I'],
    'Mechanical Engineering': ['ME 205: Intro to Thermodynamics', 'ME 210: Engineering Dynamics', 'ME 211: Fluid Mechanics I', 'ME 250: Intro to Engineering Design', 'ME 308: Mechanical Vibrations', 'ME 321: Heat Transfer', 'ME 325: Mechanical Design I', 'ME 396: Senior Design I'],
    'Meteorology': ['EAES 101: Global Environmental Change', 'EAES 111: Earth, Energy, Environment', 'EAES 215: Intro to Environmental Science', 'EAES 320: Water Resources', 'EAES 444: Geophysics', 'PHYS 141: General Physics I', 'CS 109: Programming for Engineers', 'MATH 180: Calculus I'],
    'Microbiology': ['BIOS 350: General Microbiology', 'BIOS 351: Microbiology Laboratory', 'BIOS 222: Cell Biology', 'BIOS 452: Biochemistry I', 'BIOS 454: Biochemistry II', 'CHEM 232: Organic Chemistry I', 'BIOS 220: Genetics', 'BIOS 450: Advanced Microbiology'],
    'Molecular Biology': ['BIOS 220: Genetics', 'BIOS 222: Cell Biology', 'BIOS 452: Biochemistry I', 'BIOS 484: Neuroscience I', 'BIOS 352: Introductory Biochemistry', 'CHEM 232: Organic Chemistry I', 'CHEM 234: Organic Chemistry II', 'BIOS 323: Molecular Biology Lab'],
    'Music': ['MUS 100: Introduction to Music', 'MUS 101: Music Theory I', 'MUS 102: Music Theory II', 'MUS 114: Jazz History', 'MUS 127: Latin American Music', 'MUS 223: Music Technology', 'MUS 230: History of Western Music I', 'MUS 300: Music Ensemble'],
    'Neuroscience': ['BIOS 286: Biology of the Brain', 'PSCH 262: Behavioral Neuroscience', 'BIOS 484: Neuroscience I', 'BIOS 485: Neuroscience II', 'PSCH 366: Cognitive Neuroscience', 'PHIL 202: Philosophy of Psychology', 'CHEM 232: Organic Chemistry I', 'BIOS 222: Cell Biology'],
    'Nuclear Engineering': ['ME 205: Intro to Thermodynamics', 'ME 321: Heat Transfer', 'PHYS 240: Fundamentals of Modern Quantum Theory', 'PHYS 411: Quantum Mechanics I', 'CME 260: Properties of Materials', 'ME 211: Fluid Mechanics I', 'MATH 220: Differential Equations', 'CS 109: Programming for Engineers'],
    'Nursing': ['NURS 210: Health Assessment', 'NURS 221: Foundations of Nursing', 'NURS 321: Nursing Care of Adults', 'NURS 331: Nursing Care of Women and Childbearing', 'NURS 341: Nursing Care of Children', 'NURS 351: Nursing Care in Mental Health', 'NURS 361: Community Health Nursing', 'BIOS 350: Microbiology'],
    'Nutrition Science': ['HN 110: Foods and Nutrition', 'HN 196: Nutrition Seminar', 'HN 202: Culture and Food', 'HN 300: Science of Foods', 'HN 302: Nutrition Education', 'HN 307: Human Nutrition and Metabolism', 'HN 410: Food Microbiology', 'CHEM 122: General Chemistry I'],
    'Philosophy': ['PHIL 100: Intro to Philosophy', 'PHIL 102: Intro to Logic', 'PHIL 103: Intro to Ethics', 'PHIL 201: Theory of Knowledge', 'PHIL 202: Philosophy of Psychology', 'PHIL 210: Symbolic Logic', 'PHIL 223: Aesthetics', 'PHIL 430: Ethics'],
    'Physics': ['PHYS 141: General Physics I', 'PHYS 142: General Physics II', 'PHYS 215: Mathematical Methods for Physicists', 'PHYS 240: Fundamentals of Modern Quantum Theory', 'PHYS 401: Electromagnetism I', 'PHYS 411: Quantum Mechanics I', 'MATH 220: Differential Equations', 'MATH 210: Calculus III'],
    'Political Science': ['POLS 101: Intro to American Government', 'POLS 130: Intro to Comparative Politics', 'POLS 184: Intro to International Relations', 'POLS 200: Methods of Political Science', 'POLS 281: US Foreign Policy', 'POLS 290: Political Theory', 'POLS 329: American Constitutional Law', 'ECON 120: Microeconomics'],
    'Psychology': ['PSCH 100: Intro to Psychology', 'PSCH 242: Intro to Research in Psychology', 'PSCH 262: Behavioral Neuroscience', 'PSCH 270: Abnormal Psychology', 'PSCH 343: Statistical Methods', 'PSCH 352: Cognition', 'PSCH 385: Developmental Psychology', 'PSCH 360: Learning and Conditioning'],
    'Public Health': ['PUBH 100: Health and the Public', 'PUBH 110: Public Health and Global Societies', 'PUBH 120: Public Health and Disease', 'PUBH 300: Critical Thinking in Public Health', 'PUBH 310: Public Health and Citizenship', 'PUBH 330: Health Equity', 'PUBH 350: Health Systems', 'STAT 101: Intro to Statistics'],
    'Social Work': ['SOC 100: Intro to Sociology', 'PSCH 100: Intro to Psychology', 'SOC 241: Social Inequalities', 'PSCH 270: Abnormal Psychology', 'SOC 245: Marriage and Family', 'SOC 485: Sociology of Social Welfare', 'PSCH 385: Developmental Psychology', 'SOC 265: Sociology of Politics'],
    'Sociology': ['SOC 100: Intro to Sociology', 'SOC 105: Social Problems', 'SOC 201: Intro to Sociological Statistics', 'SOC 224: Gender and Society', 'SOC 225: Racial and Ethnic Groups', 'SOC 300: Sociological Research Methods', 'SOC 385: Sociological Theory', 'SOC 402: Intermediate Sociological Statistics'],
    'Theater': ['THTR 101: Intro to Theatre', 'THTR 141: Acting I', 'THTR 201: Modern Theatre', 'THTR 230: Script Analysis', 'THTR 250: Scenic Design I', 'THTR 257: Costume Design I', 'THTR 341: Acting III', 'THTR 449: Senior Project'],
    'Veterinary Science': ['BIOS 110: Biology of Cells', 'BIOS 120: Biology of Populations', 'CHEM 122: General Chemistry I', 'CHEM 232: Organic Chemistry I', 'PHYS 141: General Physics I', 'BIOS 350: Microbiology', 'BIOS 220: Genetics', 'BIOS 272: Comparative Vertebrate Anatomy']
}

print(len(course_catalog))
print(len(unique_majors))

import random
def assign_random_courses(major):
    # Retrieve the course list for the student's major
    available_courses = course_catalog.get(major, [])

    # Randomly select 2 courses (or fewer if the list is short)
    k = min(2, len(available_courses))
    if k == 0:
        return [] # Return empty list if no courses found
    return random.sample(available_courses, k)

# Apply this to your dataframe
df['Courses'] = df['Major'].apply(assign_random_courses)

# 3. Verify the result
print(df[['Major', 'Courses']].head())

# Check for students with empty course lists
# We apply the len() function to each list in the 'Courses' column
empty_courses_mask = df['Courses'].apply(len) == 0
num_empty = empty_courses_mask.sum()

print(f"Number of students with no courses assigned: {num_empty}")

if num_empty > 0:
    print("\nMajors resulting in empty course lists:")
    # Show unique majors that didn't get courses
    print(df.loc[empty_courses_mask, 'Major'].unique())

    print("\nExample rows with empty courses:")
    display(df[empty_courses_mask][['Name', 'Major', 'Courses']].head())

import random
import pandas as pd

# 1. DEFINE VALID UIC TIME BLOCKS (30-min chunks)
days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
all_slots = []
for d in days:
    for h in range(8, 18): # 8 AM to 6 PM
        for m in [0, 30]:
            all_slots.append(f"{d}_{h:02d}:{m:02d}")

all_slots_set = set(all_slots)

# 2. CREATE A MASTER SCHEDULE FOR EVERY COURSE IN YOUR CATALOG
# This ensures that everyone taking "CS 111" gets the SAME time slots.

mw_starts = [8, 9.5, 11, 12.5, 14, 15.5]
tth_starts = [8, 9.5, 11, 12.5, 14, 15.5]

def generate_class_time_blocks():
    """Generates 3 blocks (1.5 hours) for a Mon/Wed or Tue/Thu pattern"""
    pattern = random.choice(['MW', 'TTh'])
    start_hour = random.choice(mw_starts)

    blocks = []
    current_days = ['Mon', 'Wed'] if pattern == 'MW' else ['Tue', 'Thu']

    for day in current_days:
        h = int(start_hour)
        m = int((start_hour % 1) * 60)

        # Add 3 blocks (0, 30, 60 mins)
        for _ in range(3):
            blocks.append(f"{day}_{h:02d}:{m:02d}")
            m += 30
            if m >= 60:
                h += 1
                m -= 60
    return blocks

# Flatten your catalog to get a list of all unique courses
all_unique_courses = set()
for major, course_list in course_catalog.items():
    for c in course_list:
        all_unique_courses.add(c)

# Create the Master Map: { "CS 111...": ['Mon_10:00', 'Mon_10:30', ...], ... }
master_course_schedule = {}
for course in all_unique_courses:
    master_course_schedule[course] = generate_class_time_blocks()

print(f"Generated schedules for {len(master_course_schedule)} unique courses.\n")

# Print the schedule for ALL courses
print("--- Master Course Schedule ---")
for course, slots in sorted(master_course_schedule.items()):
    print(f"{course}: {slots}")

def calculate_student_schedule(row):
    my_courses = row['Courses'] # List like ['CS 111...', 'MATH 180...']

    busy_slots = set()

    # Look up the "Official" time for each course
    for course_name in my_courses:
        if course_name in master_course_schedule:
            # Add the specific blocks for this course
            course_times = master_course_schedule[course_name]
            busy_slots.update(course_times)

    # Calculate Free Slots (The Inverse)
    # We want to link students based on when they are FREE
    free_slots = list(all_slots_set - busy_slots)

    return free_slots

# Apply to DataFrame
df['Free_Slots'] = df.apply(calculate_student_schedule, axis=1)

# Preview
print(df[['Name', 'Courses', 'Free_Slots']].head())



# Save the updated DataFrame with new columns to a CSV file
output_filename = 'profiles_updated.csv'
df.to_csv(output_filename, index=False)
print(f"DataFrame successfully saved to {output_filename}")

from google.colab import drive
import shutil
import os

# 1. Mount Google Drive
# This will prompt for authorization if not already mounted
drive.mount('/content/drive')

# 2. Define Source and Destination
source_file = 'profiles_updated.csv'
destination_folder = '/content/drive/MyDrive/'

# 3. Copy the file
if os.path.exists(source_file):
    try:
        shutil.copy(source_file, destination_folder)
        print(f"Success! '{source_file}' has been copied to '{destination_folder}'")
    except Exception as e:
        print(f"Error copying file: {e}")
else:
    print(f"Error: Source file '{source_file}' not found in the current directory.")

df.info()

"""### Mount Google Drive
This cell mounts your Google Drive to the `/content/drive` directory, allowing you to access files stored there.
"""

from google.colab import drive
drive.mount('/content/drive')

"""## 2. Feature Engineering: Text Concatenation

Here, we combine relevant text-based columns (like Hobbies, Unique Quality, and Story) into a single 'profile\_text' column. This consolidated text will be used to generate text embeddings.
"""

# Define the columns that contain narrative text
text_columns = ['Hobbies', 'Unique Quality', 'Story']

# Fill any potential missing values in these columns with an empty string
# This prevents errors and ensures consistency.
for col in text_columns:
    df[col] = df[col].fillna('')

# Concatenate the text columns into a new 'profile_text' column.
# We join the text from each specified column with a space in between.
df['profile_text'] = df[text_columns].apply(lambda row: ' '.join(row.values.astype(str)), axis=1)

# Display the new column for the first few students to verify
print("\nConsolidated Profile Text for the first 2 students:")
print(df[['Name', 'profile_text']].head(2))

"""## 3. Install Sentence Transformers, Torch etc.

This cell installs the necessary library for generating sentence embeddings.
"""

!pip install -q torch-geometric sentence-transformers

"""## 4. Generate Text Embeddings

This section uses a pre-trained sentence transformer model to convert the 'profile\_text' into numerical vectors (embeddings). These embeddings capture the semantic meaning of the text.
"""

# Import the SentenceTransformer class and the numpy library for numerical operations
from sentence_transformers import SentenceTransformer
import numpy as np

# 1. Load the pre-trained model
# 'all-MiniLM-L6-v2' is a fantastic general-purpose model. It's fast and highly effective
# for semantic similarity tasks, making it ideal for our project.
# The library will download the model automatically on its first run.
print("Loading the Sentence Transformer model...")
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')
print("Model loaded successfully.")

# 2. Encode the profile_text column
# We convert the 'profile_text' column to a list of strings to feed into the model.
# The model.encode() function will then process each string and output a vector.
# show_progress_bar=True is helpful to monitor progress on larger datasets.
print("\nGenerating text embeddings for all profiles... (This may take a moment)")
text_embeddings = model.encode(df['profile_text'].tolist(), show_progress_bar=True)

# 3. Inspect the result
# The output is a NumPy array where each row is the numerical vector (embedding)
# for a corresponding student in your DataFrame.
print(f"\nEmbeddings generated. The shape of our embeddings matrix is: {text_embeddings.shape}")

# 4. Save the embeddings
# This is a good practice. Generating embeddings can take a few minutes.
# By saving them to a file, you can easily load them back in later
# without needing to re-run the encoding process.
np.save('text_embeddings.npy', text_embeddings)
print("Text embeddings have been saved to 'text_embeddings.npy'")

"""## 5. Feature Engineering: Combine and Normalize Features

We combine the numerical features (Age, GPA), one-hot encoded categorical features (Sex, Major, Year, Country, State/Province), and the text embeddings into a single, unified vector for each student. These vectors are then normalized.
"""

# --- Step 1: Import Necessary Libraries ---
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, normalize


# --- Step 2: Define Numerical and Categorical Features ---
# Based on your data, we'll specify which columns to treat as categorical
# and which to treat as numerical.
categorical_features =['Sex','Major','Year','Country','State/Province']
numerical_features = ['Age', 'GPA']

# --- Step 3: Process Categorical Features with One-Hot Encoding ---
# This technique converts each category into a new binary column (0 or 1).
# It's the standard way to prepare categorical data for machine learning
# because it doesn't create a false sense of order between categories.
print("Processing categorical features with one-hot encoding...")
categorical_df = pd.get_dummies(df[categorical_features], prefix_sep='_', drop_first=True)
print(f"Shape of the one-hot encoded data: {categorical_df.shape}")

# --- Step 4: Process Numerical Features with Standardization ---
# This rescales the numerical data so that each feature has a mean of 0
# and a standard deviation of 1. This is crucial to prevent features with
# larger values (like Age) from disproportionately influencing the model.
print("\nProcessing numerical features with standardization...")
scaler = StandardScaler()
numerical_scaled = scaler.fit_transform(df[numerical_features])
print(f"Shape of the standardized numerical data: {numerical_scaled.shape}")

# --- Step 5: Load Your Pre-Generated Text Embeddings ---
# Load the text_embeddings.npy file you created in the previous step.
print("\nLoading the saved text embeddings...")
text_embeddings = np.load('text_embeddings.npy')
print(f"Shape of the loaded text embeddings: {text_embeddings.shape}")

# --- Step 6: Combine All Features into a Unified Vector ---
# Now we'll merge the three processed feature sets into a single, wide vector for each user.
# We use np.hstack to stack them horizontally.
print("\nCombining all features to create the unified user vectors...")
# Normalize each feature group individually
cat_norm = normalize(categorical_df, norm='l2', axis=1)
num_norm = normalize(numerical_scaled, norm='l2', axis=1)
text_norm = text_embeddings / np.linalg.norm(text_embeddings, axis=1, keepdims=True)

# Combine and then normalize again
combined_features = np.hstack([cat_norm, num_norm, text_norm])

# Final L2 normalization
row_norms = np.linalg.norm(combined_features, axis=1, keepdims=True)
row_norms[row_norms == 0] = 1e-10
unified_user_vectors = combined_features / row_norms
print(f"Shape of the combined feature matrix: {combined_features.shape}")

print(f"Shape of the final normalized user vectors: {unified_user_vectors.shape}")

# --- Step 8: Save the Final Unified Vectors ---
# This is the final output of our feature engineering. This file contains the
# complete numerical representation of every student in your dataset.
np.save('unified_user_vectors.npy', unified_user_vectors)
print("\nUnified user vectors successfully created and saved to 'unified_user_vectors.npy'")

"""## 6. Calculate Similarity Matrix and Generate Recommendations

This section calculates the cosine similarity between all pairs of unified user vectors to create a similarity matrix. A function is then defined and used to generate friend recommendations for a given student based on these similarity scores.
"""

# --- Step 1: Import Necessary Libraries and Load Data ---
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Load the original DataFrame to get student names for our recommendations.
# Make sure to use the same CSV file you started with.
df = pd.read_csv('profiles_processed.csv')

# Load the final unified user vectors that you saved in the last step.
print("Loading the unified user vectors...")
unified_user_vectors = np.load('unified_user_vectors.npy')
print(f"Successfully loaded user vectors with shape: {unified_user_vectors.shape}")


# --- Step 2: Calculate the Similarity Matrix ---
# This step remains the same.
print("\nCalculating the user-to-user similarity matrix...")
similarity_matrix = cosine_similarity(unified_user_vectors)
similarity_matrix = np.clip(similarity_matrix, -1, 1)
print(f"Similarity matrix calculated. Shape: {similarity_matrix.shape}")


# --- Step 3: Build a More Robust Recommendation Function ---

# Create a mapping from student_id to the DataFrame's integer position (index).
# This is the crucial fix to prevent mismatches.
id_to_index = pd.Series(df.index, index=df.student_id)


def get_friend_recommendations(student_id, top_n=10):
    """
    Generates friend recommendations for a given student ID using a robust index mapping.

    Args:
        student_id (int): The ID of the student for whom to generate recommendations.
        top_n (int): The number of top recommendations to return.

    Returns:
        A pandas DataFrame with the names and IDs of recommended students and their similarity scores.
    """
    # Check if the student_id exists in our mapping
    if student_id not in id_to_index:
        return f"Student with ID {student_id} not found."

    # Get the integer index (position) of the student from our mapping
    student_index = id_to_index[student_id]

    # Get the similarity scores for this student against all other students
    similarity_scores = list(enumerate(similarity_matrix[student_index]))

    # Sort the students based on their similarity scores in descending order
    sorted_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    # Get the indices and scores of the top N most similar students.
    # We start from index 1 to exclude the student themselves.
    top_students = sorted_scores[1:top_n+1]

    # Extract only the integer indices from the sorted list of tuples
    top_student_indices = [i[0] for i in top_students]

    # Extract the similarity scores from the sorted list of tuples
    top_student_scores = [i[1] for i in top_students]

    # Get the names and details of the top N students using their integer positions (.iloc)
    recommended_students = df.iloc[top_student_indices]

    # Create a DataFrame to display the results cleanly
    # Adding student_id to the output makes it easier to verify.
    recommendations_df = pd.DataFrame({
        'Name': recommended_students['Name'],
        'student_id': recommended_students['student_id'],
        'Similarity Score': top_student_scores
    })

    return recommendations_df

# --- Step 4: Get Recommendations for an Example Student ---
# Let's test our corrected function.
example_student_id = 15001
student_name = df[df['student_id'] == example_student_id]['Name'].values

print(f"\n--- Generating Top 10 Friend Recommendations for {student_name} (ID: {example_student_id}) ---")
recommendations = get_friend_recommendations(example_student_id, top_n=10)

# Display the recommendations
print(recommendations)

"""## 7. Visualize User Embeddings

This final section uses dimensionality reduction techniques (like t-SNE) to reduce the high-dimensional user vectors to 2D, allowing for visualization of the user embedding space and highlighting specific users.
"""

# --- Visualization of User Embeddings ---

from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Load your unified vectors
unified_user_vectors = np.load('unified_user_vectors.npy')
df = pd.read_csv('profiles_processed.csv')

# ----- 1. Dimensionality Reduction ----
reducer = TSNE(n_components=2, perplexity=40, learning_rate=200, random_state=42)
emb_2d = reducer.fit_transform(unified_user_vectors)

# ----- 2. Plot -----
plt.figure(figsize=(12, 8))
plt.scatter(emb_2d[:,0], emb_2d[:,1], s=8, alpha=0.5, c='steelblue')
plt.title("User Embedding Space (t-SNE projection)")
plt.xlabel("Dimension 1"); plt.ylabel("Dimension 2")

# Highlight one or more students
def highlight(name, color='red', label=None):
    idx = df.index[df['Name'].str.contains(name, case=False, na=False)]
    if len(idx) > 0:
        plt.scatter(emb_2d[idx,0], emb_2d[idx,1], s=80, color=color, label=label or name)
        for i in idx:
            plt.text(emb_2d[i,0]+0.5, emb_2d[i,1]+0.5, df.loc[i,'Name'].split()[0], fontsize=9)

highlight("Thomas Ibarra", color='red')
highlight("Robert Burton", color='orange')
plt.legend()
plt.show()



import torch, torch_geometric
from sentence_transformers import SentenceTransformer
print(torch.__version__)
print(torch_geometric.__version__)
print("CUDA available:", torch.cuda.is_available())

# ============================================================
# SOCIAL HUB FRIEND RECOMMENDER - GRAPH NEURAL NETWORK (GNN)
# ============================================================

# ---- 0. Imports ----
import os, numpy as np, pandas as pd, torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import roc_auc_score, average_precision_score, roc_curve, precision_recall_curve, auc
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import seaborn as sns

from torch_geometric.data import Data
from torch_geometric.utils import to_undirected, remove_self_loops
from torch_geometric.transforms import RandomLinkSplit
from torch_geometric.nn import SAGEConv

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# ---- 1. Load your embeddings + student data ----
X = np.load("unified_user_vectors.npy").astype(np.float32)
df = pd.read_csv("profiles_processed.csv")
assert len(df) == X.shape[0], "Mismatch between df rows and embeddings!"

num_nodes, feat_dim = X.shape
print(f"Nodes: {num_nodes}, Feature dim: {feat_dim}")

# ---- 2. Build sparse k-NN graph (synthetic friendships) ----
k = 8  # neighbors per node
nbrs = NearestNeighbors(n_neighbors=k+1, metric="cosine")
nbrs.fit(X)
dist, idx = nbrs.kneighbors(X)

edge_src, edge_dst = [], []
for i in range(num_nodes):
    for j in idx[i][1:]:
        edge_src.append(i)
        edge_dst.append(int(j))
edge_index = torch.tensor([edge_src, edge_dst], dtype=torch.long)
edge_index, _ = remove_self_loops(edge_index)
edge_index = to_undirected(edge_index)
print("Edges:", edge_index.shape[1])

# ---- 3. Wrap into a PyG Data object + train/val/test split ----
x = torch.from_numpy(X)
data = Data(x=x, edge_index=edge_index)
splitter = RandomLinkSplit(num_val=0.1, num_test=0.1, is_undirected=True,
                           add_negative_train_samples=True)
train_data, val_data, test_data = splitter(data)
print("Split done.")

# ---- 4. Define GraphSAGE model ----
class GraphSAGE(nn.Module):
    def __init__(self, in_dim, hidden=256, out_dim=128):
        super().__init__()
        self.conv1 = SAGEConv(in_dim, hidden)
        self.conv2 = SAGEConv(hidden, out_dim)
    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        return F.normalize(x, p=2, dim=-1)

def edge_score(z, edge_label_index):
    src, dst = edge_label_index
    return (z[src] * z[dst]).sum(dim=-1)

# ---- 5. Training setup ----
model = GraphSAGE(in_dim=feat_dim).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=5e-3, weight_decay=1e-4)

def run_epoch(part, optimizer=None):
    model.train(mode=optimizer is not None)
    x = part.x.to(device)
    z = model(x, train_data.edge_index.to(device))  # always use training graph
    logits = edge_score(z, part.edge_label_index.to(device))
    labels = part.edge_label.to(device).float()
    loss = F.binary_cross_entropy_with_logits(logits, labels)

    with torch.no_grad():
        probs = torch.sigmoid(logits).cpu().numpy()
        y_true = labels.cpu().numpy()
        auc_score = roc_auc_score(y_true, probs)
        ap_score  = average_precision_score(y_true, probs)

    if optimizer is not None:
        optimizer.zero_grad(); loss.backward(); optimizer.step()
    return float(loss.item()), float(auc_score), float(ap_score)

# ---- 6. Train model ----
train_losses, val_losses, train_aucs, val_aucs, train_aps, val_aps = [], [], [], [], [], []
best_val_auc, best_state = -1, None

for epoch in range(1, 51):
    tr_loss, tr_auc, tr_ap = run_epoch(train_data, optimizer)
    with torch.no_grad():
        vl_loss, vl_auc, vl_ap = run_epoch(val_data)
    train_losses.append(tr_loss); val_losses.append(vl_loss)
    train_aucs.append(tr_auc); val_aucs.append(vl_auc)
    train_aps.append(tr_ap); val_aps.append(vl_ap)

    if vl_auc > best_val_auc:
        best_val_auc = vl_auc
        best_state = {k:v.cpu() for k,v in model.state_dict().items()}

    if epoch % 5 == 0:
        print(f"Epoch {epoch:02d} | train loss {tr_loss:.4f}, AUC {tr_auc:.3f} | val loss {vl_loss:.4f}, AUC {vl_auc:.3f}")

model.load_state_dict({k:v.to(device) for k,v in best_state.items()})
print("Best val AUC:", best_val_auc)

# ---- 7. Test evaluation ----
with torch.no_grad():
    te_loss, te_auc, te_ap = run_epoch(test_data)
print(f"TEST | loss {te_loss:.4f}, AUC {te_auc:.3f}, AP {te_ap:.3f}")

# ============================================================
# VISUALIZATIONS
# ============================================================

# ---- A. Training Curves (Loss, AUC, AP) ----
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.plot(train_losses, label="Train", marker='o')
plt.plot(val_losses, label="Val", marker='o')
plt.title("Loss Curve")
plt.xlabel("Epoch"); plt.ylabel("BCE Loss"); plt.legend(); plt.grid(alpha=0.3)

plt.subplot(1,3,2)
plt.plot(train_aucs, label="Train", marker='o')
plt.plot(val_aucs, label="Val", marker='o')
plt.title("AUC Curve")
plt.xlabel("Epoch"); plt.ylabel("AUC"); plt.legend(); plt.grid(alpha=0.3)

plt.subplot(1,3,3)
plt.plot(train_aps, label="Train", marker='o')
plt.plot(val_aps, label="Val", marker='o')
plt.title("Average Precision Curve")
plt.xlabel("Epoch"); plt.ylabel("AP"); plt.legend(); plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

# ---- B. ROC and Precision-Recall Curves (Test) ----
model.eval()
with torch.no_grad():
    z = model(data.x.to(device), train_data.edge_index.to(device))
    logits = edge_score(z, test_data.edge_label_index.to(device))
    probs = torch.sigmoid(logits).cpu().numpy()
    labels = test_data.edge_label.cpu().numpy()

fpr, tpr, _ = roc_curve(labels, probs)
prec, rec, _ = precision_recall_curve(labels, probs)

plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(fpr, tpr, label=f"AUC = {auc(fpr, tpr):.3f}", color='royalblue')
plt.plot([0,1],[0,1],'--',color='gray')
plt.title("ROC Curve"); plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate"); plt.legend()

plt.subplot(1,2,2)
plt.plot(rec, prec, color='green')
plt.title("Precision–Recall Curve")
plt.xlabel("Recall"); plt.ylabel("Precision")

plt.tight_layout()
plt.show()

# ---- C. Histogram of Predicted Edge Probabilities ----
plt.hist(probs[labels==1], bins=30, alpha=0.7, label='Positive (Real Edges)')
plt.hist(probs[labels==0], bins=30, alpha=0.7, label='Negative (Random Pairs)')
plt.xlabel('Predicted Probability'); plt.ylabel('Frequency')
plt.title('Predicted Edge Probability Distribution')
plt.legend()
plt.show()

# ---- D. Node Degree Distribution ----
deg = np.bincount(edge_index[0].numpy())
plt.hist(deg, bins=20, color='steelblue', alpha=0.8)
plt.title('Node Degree Distribution')
plt.xlabel('Degree'); plt.ylabel('Frequency')
plt.show()

# ---- E. t-SNE Visualization of Node Embeddings ----
with torch.no_grad():
    z = model(data.x.to(device), train_data.edge_index.to(device)).cpu().numpy()

tsne = TSNE(n_components=2, perplexity=40, learning_rate=200, random_state=42)
z2 = tsne.fit_transform(z)

plt.figure(figsize=(10,8))
sns.scatterplot(x=z2[:,0], y=z2[:,1], s=8, alpha=0.7)
plt.title("2D Visualization of GraphSAGE Node Embeddings (t-SNE)")
plt.xlabel("Dim-1"); plt.ylabel("Dim-2")
plt.show()

# ---- Optional: Color by Major ----
colors = pd.factorize(df['Major'])[0]
sns.scatterplot(x=z2[:,0], y=z2[:,1], hue=colors, palette='tab10', s=10, alpha=0.8, legend=False)
plt.title("Embedding Clusters Colored by Major")
plt.show()

## 8. Heterogenous GraphSage

import numpy as np
from google.colab import drive
import os

# Mount Google Drive if not already mounted
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# Define the path to the mpnet_embeddings.npy file in your Drive
embeddings_path = '/content/drive/MyDrive/mpnet_embeddings.npy'

# Load the embeddings
if os.path.exists(embeddings_path):
    loaded_mpnet_embeddings = np.load(embeddings_path)
    print(f"Successfully loaded embeddings with shape: {loaded_mpnet_embeddings.shape}")
else:
    print(f"Error: File not found at {embeddings_path}")

import os
import ast
import torch
import numpy as np
import pandas as pd
import torch.nn.functional as F
from torch_geometric.data import HeteroData
from torch_geometric.nn import SAGEConv, to_hetero
import torch_geometric.transforms as T
from sentence_transformers import SentenceTransformer
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import NearestNeighbors

# ==============================================================================
# 1. SETUP & CONFIGURATION
# ==============================================================================
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"✅ Using device: {device}")

# ==============================================================================
# 2. DATA LOADING & FEATURE ENGINEERING
# ==============================================================================
print("\n[Step 1/5] Loading and Processing Data...")

# Load your CSV
df = pd.read_csv("profiles_processed.csv")

# --- A. Text Embeddings (The "Soul" of the user) ---
# We combine Unique Quality and Story to get a deep semantic vector.
embeddings_file_path = '/content/drive/MyDrive/mpnet_embeddings.npy' # Corrected path to Google Drive

if os.path.exists(embeddings_file_path):
    print("   -> Loading cached MPNet embeddings from Drive...")
    text_embeddings = np.load(embeddings_file_path)
else:
    print("   -> Generating MPNet embeddings (this takes time once)...")
    # Combine text columns
    df['full_text'] = df['Unique Quality'] + ". " + df['Story']

    # Load MPNet (High quality semantic model)
    encoder = SentenceTransformer('all-mpnet-base-v2')
    text_embeddings = encoder.encode(df['full_text'].tolist(), show_progress_bar=True)

    # Save for future runs to the specified path
    np.save(embeddings_file_path, text_embeddings)

# --- B. Numerical Features (Age, GPA, Year) ---
# Map 'Year' string to integer
year_map = {'Freshman': 1, 'Sophomore': 2, 'Junior': 3, 'Senior': 4, 'Graduate': 5, 'PhD': 6}
# Handle cases where Year might not be in map (defaults to 1)
df['Year_Num'] = df['Year'].map(year_map).fillna(1)

scaler = StandardScaler()
# Normalize Age, GPA, and Year so they are on same scale as embeddings
numerical_feats = scaler.fit_transform(df[['Age', 'GPA', 'Year_Num']].values)

# --- C. Categorical Features (Sex) ---
le_sex = LabelEncoder()
sex_feats = le_sex.fit_transform(df['Sex']).reshape(-1, 1)

# --- D. Combine All User Features ---
# Structure: [Text(768) | Age(1) | GPA(1) | Year(1) | Sex(1)] = 772 Dimensions
user_features = np.hstack([text_embeddings, numerical_feats, sex_feats])
user_x = torch.tensor(user_features, dtype=torch.float)

print(f"   -> User Feature Matrix Shape: {user_x.shape}")

# ==============================================================================
# 3. GRAPH CONSTRUCTION (The "Pinterest Structure")
# ==============================================================================
print("\n[Step 2/5] Building Heterogeneous Graph...")

data = HeteroData()

# --- Nodes ---
# 1. Users
data['user'].x = user_x
data['user'].num_nodes = len(df)

# 2. Majors
unique_majors = df['Major'].unique()
major_map = {m: i for i, m in enumerate(unique_majors)}
data['major'].num_nodes = len(unique_majors)
# Feature for Major is just Identity (One-Hot)
data['major'].x = torch.eye(len(unique_majors))

# 3. Hobbies
# Parse the stringified lists "['art', 'code']" -> list
hobby_set = set()
user_hobby_pairs = []

for idx, row in df.iterrows():
    try:
        # Safe eval to convert string to list
        h_list = ast.literal_eval(row['Hobbies']) if isinstance(row['Hobbies'], str) else row['Hobbies']
        for h in h_list:
            h_clean = h.strip().lower()
            hobby_set.add(h_clean)
            user_hobby_pairs.append((idx, h_clean))
    except:
        continue # Skip malformed rows

unique_hobbies = list(hobby_set)
hobby_map = {h: i for i, h in enumerate(unique_hobbies)}
data['hobby'].num_nodes = len(unique_hobbies)
# Feature for Hobby is Identity
data['hobby'].x = torch.eye(len(unique_hobbies))

# --- Edges ---

# 1. User -> studies -> Major
u_indices = []
m_indices = []
for idx, row in df.iterrows():
    if row['Major'] in major_map:
        u_indices.append(idx)
        m_indices.append(major_map[row['Major']])

data['user', 'studies', 'major'].edge_index = torch.tensor([u_indices, m_indices], dtype=torch.long)

# 2. User -> likes -> Hobby
u_h_src = []
h_dst = []
for u_idx, h_name in user_hobby_pairs:
    if h_name in hobby_map:
        u_h_src.append(u_idx)
        h_dst.append(hobby_map[h_name])

data['user', 'likes', 'hobby'].edge_index = torch.tensor([u_h_src, h_dst], dtype=torch.long)

# --- Reverse Edges ---
# Crucial: Allows the GNN to pass info BACK from Major/Hobby to User
data = T.ToUndirected()(data)

# Move to GPU/CPU
data = data.to(device)
print(f"   -> Graph Ready: {data}")

import shutil
import os
from google.colab import drive

# 1. Mount Google Drive (if not already mounted)
drive.mount('/content/drive')

# 2. Define the files you want to save
files_to_save = [
    'text_embeddings.npy',
    'unified_user_vectors.npy',
    'mpnet_embeddings.npy'
]

# 3. Destination path in Google Drive
# You can change this to a specific folder, e.g., '/content/drive/MyDrive/Colab Data/'
destination_folder = '/content/drive/MyDrive/'

# 4. Copy the files
print(f"Copying files to {destination_folder}...")
for filename in files_to_save:
    if os.path.exists(filename):
        try:
            shutil.copy(filename, destination_folder)
            print(f"✅ Successfully saved: {filename}")
        except Exception as e:
            print(f"❌ Error saving {filename}: {e}")
    else:
        print(f"⚠️ File not found (skipping): {filename}")

import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import SAGEConv, to_hetero

# ==============================================================================
# 4. DEFINE IMPROVED MODEL (Wider + Dropout + Norm)
# ==============================================================================
print("\n[Step 3/5] Initializing Improved PinSage-style Model...")

class SocialGNN(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels):
        super().__init__()
        # 1. Wider Layers: We accept -1 (lazy init) to match input dim automatically
        self.conv1 = SAGEConv((-1, -1), hidden_channels)

        # 2. Normalization Layer (Optional but helps training stability)
        self.bn = nn.BatchNorm1d(hidden_channels)

        # 3. Output Layer
        self.conv2 = SAGEConv((-1, -1), out_channels)

        # 4. Dropout: Randomly zero out 20% of neurons to prevent overfitting
        self.dropout = nn.Dropout(p=0.2)

    def forward(self, x, edge_index):
        # Layer 1: Message Passing
        x = self.conv1(x, edge_index)
        x = self.bn(x) # Batch Norm
        x = F.relu(x)  # Activation
        x = self.dropout(x) # Dropout

        # Layer 2: Message Passing
        x = self.conv2(x, edge_index)

        # 5. L2 Normalization
        # This forces all vectors to have length 1.
        # This is CRITICAL because we use Cosine Similarity later.
        return F.normalize(x, p=2, dim=-1)

# --- HYPERPARAMETERS ---
# Old: hidden=64, out=32
# New: hidden=256, out=64 (Much capable of holding MPNet's 768-dim info)
model = SocialGNN(hidden_channels=256, out_channels=64)

# Convert generic GNN to Heterogeneous GNN
# aggr='sum' or 'mean' works well. 'sum' is often better for recommender systems.
model = to_hetero(model, data.metadata(), aggr='sum').to(device)

#optimizer = torch.optim.Adam(model.parameters(), lr=0.001) # Lower LR slightly for larger model

optimizer = torch.optim.Adam(model.parameters(), lr=0.0005, weight_decay=1e-4)

# ==============================================================================
# 4. DEFINE MODEL (Hetero GraphSAGE)
# ==============================================================================
print("\n[Step 3/5] Initializing PinSage-style Model...")

class SocialGNN(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels):
        super().__init__()
        # SAGEConv aggregates neighbors
        self.conv1 = SAGEConv((-1, -1), hidden_channels)
        self.conv2 = SAGEConv((-1, -1), out_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        return x

# Input dimension is -1 (lazy load), Hidden 64, Output 32
model = SocialGNN(hidden_channels=64, out_channels=32)

# Convert generic GNN to Heterogeneous GNN
# This creates specific weights for (user-major) vs (user-hobby)
model = to_hetero(model, data.metadata(), aggr='sum').to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.005)

# ==============================================================================
# 5. TRAINING LOOP
# ==============================================================================
print("\n[Step 4/5] Training Embeddings...")

def train():
    model.train()
    optimizer.zero_grad()

    # 1. Forward Pass: Get embeddings for all nodes
    out_dict = model(data.x_dict, data.edge_index_dict)

    # 2. Define Loss: Link Prediction on User-Hobby edges
    # We want Users to be close to Hobbies they actually like

    # Get edge indices for 'user' -> 'likes' -> 'hobby'
    # Note: After ToUndirected, PyG might rename edges. We use original names if possible
    # or access via the edge_types list.
    edge_type = ('user', 'likes', 'hobby')
    src, dst = data[edge_type].edge_index

    user_embed = out_dict['user'][src]
    hobby_embed = out_dict['hobby'][dst]

    # Positive Score (Dot product)
    pos_score = (user_embed * hobby_embed).sum(dim=1)

    # Negative Sampling (Random mismatching hobbies)
    rand_dst = torch.randint(0, data['hobby'].num_nodes, (len(src),), device=device)
    neg_hobby_embed = out_dict['hobby'][rand_dst]
    neg_score = (user_embed * neg_hobby_embed).sum(dim=1)

    # Margin Ranking Loss or BPR Loss
    # Maximize (Pos - Neg)
    loss = -torch.log(torch.sigmoid(pos_score - neg_score) + 1e-15).mean()

    loss.backward()
    optimizer.step()
    return loss.item()

# Train for 50 epochs (Usually sufficient for convergence on this size)
for epoch in range(1, 51):
    loss = train()
    if epoch % 10 == 0:
        print(f"   Epoch {epoch:02d} | Loss: {loss:.4f}")

# ==============================================================================
# 6. GENERATE RECOMMENDATIONS
# ==============================================================================
print("\n[Step 5/5] Generating Recommendations...")

model.eval()
with torch.no_grad():
    # Get the final "Learned" representations
    embeddings = model(data.x_dict, data.edge_index_dict)
    user_vectors = embeddings['user'].cpu().numpy()

# Use KNN to find similar users based on the learned vectors
# These vectors now contain: Story Semantics + Age/Year Info + Graph Structure
knn = NearestNeighbors(n_neighbors=6, metric='cosine')
knn.fit(user_vectors)

def get_recommendations(user_id_index):
    # Get neighbors
    distances, indices = knn.kneighbors([user_vectors[user_id_index]])

    # Display
    me = df.iloc[user_id_index]
    print(f"\n🔵 TARGET USER: {me['Name']}")
    print(f"   Major: {me['Major']} | Year: {me['Year']} | Age: {me['Age']}")
    print(f"   Unique Quality: {me['Unique Quality']}")
    print(f"   Hobbies: {me['Hobbies']}")
    print("="*60)

    # Iterate neighbors (skip 0 because it is the user themselves)
    for i, idx in enumerate(indices[0][1:]):
        friend = df.iloc[idx]
        score = 1 - distances[0][i+1] # Convert cosine dist to similarity

        print(f"🟢 RECOMMENDATION #{i+1} (Similarity: {score:.3f})")
        print(f"   Name: {friend['Name']}")
        print(f"   Major: {friend['Major']} | Year: {friend['Year']} | Age: {friend['Age']}")
        print(f"   Unique Quality: {friend['Unique Quality']}")
        print(f"   Hobbies: {friend['Hobbies']}")
        print("-" * 30)

# --- DEMO: Recommend for the first 3 users in the dataframe ---
for i in range(3):
    get_recommendations(i)

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.manifold import TSNE
from torch_geometric.transforms import RandomLinkSplit

# ==============================================================================
# 1. PREPARE TRAIN / VAL / TEST SPLIT
# ==============================================================================
# We split the 'user-likes-hobby' edges.
# We keep 80% for Message Passing/Training, 10% for Validation, 10% for Testing.
transform = RandomLinkSplit(
    num_val=0.1,
    num_test=0.1,
    is_undirected=True,
    edge_types=[('user', 'likes', 'hobby')],
    add_negative_train_samples=False
)
train_data, val_data, test_data = transform(data)

# Lists to store metrics for plotting
history = {
    'loss': [],
    'val_auc': [],
    'val_ap': [] # Average Precision
}

# ==============================================================================
# 2. TRAINING WITH METRICS
# ==============================================================================

def train_step():
    model.train()
    optimizer.zero_grad()

    # Run model on TRAIN graph
    out = model(train_data.x_dict, train_data.edge_index_dict)

    # Get training edges
    edge_type = ('user', 'likes', 'hobby')
    src, dst = train_data[edge_type].edge_label_index

    # Calculate Scores
    pos_score = (out['user'][src] * out['hobby'][dst]).sum(dim=-1)

    # Negative Samples
    neg_dst = torch.randint(0, data['hobby'].num_nodes, (len(src),), device=device)
    neg_score = (out['user'][src] * out['hobby'][neg_dst]).sum(dim=-1)

    # BPR Loss
    loss = -torch.log(torch.sigmoid(pos_score - neg_score) + 1e-15).mean()
    loss.backward()
    optimizer.step()
    return loss.item()

@torch.no_grad()
def test_step(data_split):
    model.eval()
    out = model(data_split.x_dict, data_split.edge_index_dict)

    edge_type = ('user', 'likes', 'hobby')
    src, dst = data_split[edge_type].edge_label_index

    # Positive Scores (Real Edges in Val Set)
    pos_score = (out['user'][src] * out['hobby'][dst]).sum(dim=-1)

    # Negative Scores (Random edges)
    # We generate equal number of negatives to calculate AUC
    neg_dst = torch.randint(0, data['hobby'].num_nodes, (len(src),), device=device)
    neg_score = (out['user'][src] * out['hobby'][neg_dst]).sum(dim=-1)

    # Metrics
    y_true = torch.cat([torch.ones(pos_score.size(0)), torch.zeros(neg_score.size(0))]).cpu().numpy()
    y_score = torch.cat([pos_score, neg_score]).sigmoid().cpu().numpy()

    auc = roc_auc_score(y_true, y_score)

    return auc, pos_score, neg_score

print("Starting Training with Visualization Tracking...")
for epoch in range(1, 1):
    loss = train_step()
    val_auc, _, _ = test_step(val_data)

    history['loss'].append(loss)
    history['val_auc'].append(val_auc)

    if epoch % 10 == 0:
        print(f"Epoch {epoch:02d} | Loss: {loss:.4f} | Val AUC: {val_auc:.4f}")

# ==============================================================================
# 3. VISUALIZATIONS
# ==============================================================================

# --- A. Training Curves ---
plt.figure(figsize=(12, 5))

# Plot Loss
plt.subplot(1, 2, 1)
plt.plot(history['loss'], label='Training Loss', color='red')
plt.title('BPR Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss (Lower is Better)')
plt.grid(True, alpha=0.3)
plt.legend()

# Plot AUC
plt.subplot(1, 2, 2)
plt.plot(history['val_auc'], label='Validation AUC', color='blue')
plt.title('Validation AUC over Epochs')
plt.xlabel('Epoch')
plt.ylabel('AUC (Higher is Better)')
plt.grid(True, alpha=0.3)
plt.legend()

plt.tight_layout()
plt.show()

# --- B. Score Distribution (Why BPR works) ---
# We want to see Positive scores pushed to the right, Negatives to the left
_, pos_scores, neg_scores = test_step(test_data)
pos_scores = pos_scores.cpu().numpy()
neg_scores = neg_scores.cpu().numpy()

plt.figure(figsize=(10, 6))
sns.histplot(pos_scores, color='green', alpha=0.5, label='Real Connections (Pos)', kde=True)
sns.histplot(neg_scores, color='red', alpha=0.5, label='Random Pairs (Neg)', kde=True)
plt.title('Distribution of Prediction Scores')
plt.xlabel('Similarity Score (Dot Product)')
plt.ylabel('Frequency')
plt.legend()
plt.show()

# --- C. t-SNE Embedding Space (The "Map") ---
print("Generating t-SNE Visualization (this may take a moment)...")

# Get final user embeddings
model.eval()
with torch.no_grad():
    all_out = model(data.x_dict, data.edge_index_dict)
    user_emb = all_out['user'].cpu().numpy()

# Reduce to 2D for plotting
# We take a sample of 2000 users to keep it fast and readable
sample_size = 2000
indices = np.random.choice(len(df), sample_size, replace=False)
user_emb_sample = user_emb[indices]
majors_sample = df.iloc[indices]['Major'].values

tsne = TSNE(n_components=2, perplexity=30, random_state=42)
z_tsne = tsne.fit_transform(user_emb_sample)

plt.figure(figsize=(12, 10))
# Plot scatter, coloring by Major to see if clusters formed
sns.scatterplot(x=z_tsne[:,0], y=z_tsne[:,1], hue=majors_sample, palette='tab10', s=60, alpha=0.7)
plt.title('User Embeddings Cluster Map (t-SNE)')
# Move legend outside
plt.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
plt.show()

import torch.nn as nn
import torch.nn.functional as F
import copy  # <--- This is the missing line
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_auc_score
from sklearn.manifold import TSNE
from torch_geometric.transforms import RandomLinkSplit
from torch_geometric.nn import SAGEConv, to_hetero

# ... rest of your code ...

# ==============================================================================
# 5. PREPARE TRAIN / VAL / TEST SPLIT
# ==============================================================================
# We split the 'user-likes-hobby' edges.
transform = RandomLinkSplit(
    num_val=0.1,
    num_test=0.1,
    is_undirected=True,
    edge_types=[('user', 'likes', 'hobby')],
    add_negative_train_samples=False
)
train_data, val_data, test_data = transform(data)

# ==============================================================================
# 6. TRAINING LOOP WITH EARLY STOPPING
# ==============================================================================

def train_step():
    model.train()
    optimizer.zero_grad()

    # Run model on TRAIN graph
    out = model(train_data.x_dict, train_data.edge_index_dict)

    # Get training edges
    edge_type = ('user', 'likes', 'hobby')
    src, dst = train_data[edge_type].edge_label_index

    # Calculate Scores (Dot Product of normalized vectors = Cosine Similarity)
    pos_score = (out['user'][src] * out['hobby'][dst]).sum(dim=-1)

    # Negative Samples
    neg_dst = torch.randint(0, data['hobby'].num_nodes, (len(src),), device=device)
    neg_score = (out['user'][src] * out['hobby'][neg_dst]).sum(dim=-1)

    # BPR Loss
    loss = -torch.log(torch.sigmoid(pos_score - neg_score) + 1e-15).mean()
    loss.backward()
    optimizer.step()
    return loss.item()

@torch.no_grad()
def test_step(data_split):
    model.eval()
    out = model(data_split.x_dict, data_split.edge_index_dict)

    edge_type = ('user', 'likes', 'hobby')
    src, dst = data_split[edge_type].edge_label_index

    pos_score = (out['user'][src] * out['hobby'][dst]).sum(dim=-1)
    neg_dst = torch.randint(0, data['hobby'].num_nodes, (len(src),), device=device)
    neg_score = (out['user'][src] * out['hobby'][neg_dst]).sum(dim=-1)

    # Metrics
    y_true = torch.cat([torch.ones(pos_score.size(0)), torch.zeros(neg_score.size(0))]).cpu().numpy()
    y_score = torch.cat([pos_score, neg_score]).sigmoid().cpu().numpy()

    auc = roc_auc_score(y_true, y_score)
    return auc, pos_score, neg_score

# --- EARLY STOPPING CONFIGURATION ---
MAX_EPOCHS = 100       # Maximum iterations
PATIENCE = 15          # Stop if no improvement for 15 epochs
best_val_auc = 0
patience_counter = 0
best_model_state = None

history = {'loss': [], 'val_auc': []}

print(f"\n[Step 4/5] Training with Early Stopping (Max {MAX_EPOCHS} epochs)...")

for epoch in range(1, MAX_EPOCHS + 1):
    loss = train_step()
    val_auc, _, _ = test_step(val_data)

    history['loss'].append(loss)
    history['val_auc'].append(val_auc)

    # Check for improvement
    if val_auc > best_val_auc:
        best_val_auc = val_auc
        best_model_state = copy.deepcopy(model.state_dict()) # Save best weights
        patience_counter = 0 # Reset timer
        print(f"Epoch {epoch:03d} | Loss: {loss:.4f} | Val AUC: {val_auc:.4f} (New Best!)")
    else:
        patience_counter += 1
        print(f"Epoch {epoch:03d} | Loss: {loss:.4f} | Val AUC: {val_auc:.4f}")

    # Stop if patience runs out
    if patience_counter >= PATIENCE:
        print(f"\n🛑 Early Stopping triggered at Epoch {epoch}!")
        print(f"   Model stopped improving. The best AUC was {best_val_auc:.4f}")
        break

# LOAD BEST WEIGHTS BEFORE CONTINUING
if best_model_state is not None:
    model.load_state_dict(best_model_state)
    print("✅ Best model weights loaded.")

# ==============================================================================
# 7. VISUALIZATIONS
# ==============================================================================

# --- A. Training Curves ---
plt.figure(figsize=(12, 5))

# Plot Loss
plt.subplot(1, 2, 1)
plt.plot(history['loss'], label='Training Loss', color='red')
plt.title('BPR Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss (Lower is Better)')
plt.grid(True, alpha=0.3)
plt.legend()

# Plot AUC
plt.subplot(1, 2, 2)
plt.plot(history['val_auc'], label='Validation AUC', color='blue')
plt.title('Validation AUC over Epochs')
plt.xlabel('Epoch')
plt.ylabel('AUC (Higher is Better)')
plt.grid(True, alpha=0.3)
plt.legend()

plt.tight_layout()
plt.show()

# --- B. Score Distribution (Why BPR works) ---
# We want to see Positive scores pushed to the right, Negatives to the left
_, pos_scores, neg_scores = test_step(test_data)
pos_scores = pos_scores.cpu().numpy()
neg_scores = neg_scores.cpu().numpy()

plt.figure(figsize=(10, 6))
sns.histplot(pos_scores, color='green', alpha=0.5, label='Real Connections (Pos)', kde=True)
sns.histplot(neg_scores, color='red', alpha=0.5, label='Random Pairs (Neg)', kde=True)
plt.title('Distribution of Prediction Scores (Test Set)')
plt.xlabel('Similarity Score (Cosine)')
plt.ylabel('Frequency')
plt.legend()
plt.show()

# --- C. t-SNE Embedding Space (The "Map") ---
print("Generating t-SNE Visualization (this may take a moment)...")

# Get final user embeddings
model.eval()
with torch.no_grad():
    all_out = model(data.x_dict, data.edge_index_dict)
    user_emb = all_out['user'].cpu().numpy()

# Reduce to 2D for plotting
# We take a sample of 2000 users to keep it fast and readable
sample_size = 2000
if len(df) < sample_size: sample_size = len(df) # Handle small datasets

indices = np.random.choice(len(df), sample_size, replace=False)
user_emb_sample = user_emb[indices]
majors_sample = df.iloc[indices]['Major'].values

tsne = TSNE(n_components=2, perplexity=30, random_state=42)
z_tsne = tsne.fit_transform(user_emb_sample)

plt.figure(figsize=(12, 10))
# Plot scatter, coloring by Major to see if clusters formed
sns.scatterplot(x=z_tsne[:,0], y=z_tsne[:,1], hue=majors_sample, palette='tab10', s=60, alpha=0.7)
plt.title('User Embeddings Cluster Map (t-SNE)')
# Move legend outside
plt.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
plt.show()

import torch.nn as nn
import torch.nn.functional as F
import copy  # <--- This is the missing line
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_auc_score
from sklearn.manifold import TSNE
from torch_geometric.transforms import RandomLinkSplit
from torch_geometric.nn import SAGEConv, to_hetero

# ... rest of your code ...

# ==============================================================================
# 5. PREPARE TRAIN / VAL / TEST SPLIT
# ==============================================================================
# We split the 'user-likes-hobby' edges.
transform = RandomLinkSplit(
    num_val=0.1,
    num_test=0.1,
    is_undirected=True,
    edge_types=[('user', 'likes', 'hobby')],
    add_negative_train_samples=False
)
train_data, val_data, test_data = transform(data)

# ==============================================================================
# 6. TRAINING LOOP WITH EARLY STOPPING
# ==============================================================================

def train_step():
    model.train()
    optimizer.zero_grad()

    # Run model on TRAIN graph
    out = model(train_data.x_dict, train_data.edge_index_dict)

    # Get training edges
    edge_type = ('user', 'likes', 'hobby')
    src, dst = train_data[edge_type].edge_label_index

    # Calculate Scores (Dot Product of normalized vectors = Cosine Similarity)
    pos_score = (out['user'][src] * out['hobby'][dst]).sum(dim=-1)

    # Negative Samples
    neg_dst = torch.randint(0, data['hobby'].num_nodes, (len(src),), device=device)
    neg_score = (out['user'][src] * out['hobby'][neg_dst]).sum(dim=-1)

    # BPR Loss
    loss = -torch.log(torch.sigmoid(pos_score - neg_score) + 1e-15).mean()
    loss.backward()
    optimizer.step()
    return loss.item()

@torch.no_grad()
def test_step(data_split):
    model.eval()
    out = model(data_split.x_dict, data_split.edge_index_dict)

    edge_type = ('user', 'likes', 'hobby')
    src, dst = data_split[edge_type].edge_label_index

    pos_score = (out['user'][src] * out['hobby'][dst]).sum(dim=-1)
    neg_dst = torch.randint(0, data['hobby'].num_nodes, (len(src),), device=device)
    neg_score = (out['user'][src] * out['hobby'][neg_dst]).sum(dim=-1)

    # Metrics
    y_true = torch.cat([torch.ones(pos_score.size(0)), torch.zeros(neg_score.size(0))]).cpu().numpy()
    y_score = torch.cat([pos_score, neg_score]).sigmoid().cpu().numpy()

    auc = roc_auc_score(y_true, y_score)
    return auc, pos_score, neg_score

# --- EARLY STOPPING CONFIGURATION ---
MAX_EPOCHS = 100       # Maximum iterations
PATIENCE = 15          # Stop if no improvement for 15 epochs
best_val_auc = 0
patience_counter = 0
best_model_state = None

history = {'loss': [], 'val_auc': []}

print(f"\n[Step 4/5] Training with Early Stopping (Max {MAX_EPOCHS} epochs)...")

for epoch in range(1, MAX_EPOCHS + 1):
    loss = train_step()
    val_auc, _, _ = test_step(val_data)

    history['loss'].append(loss)
    history['val_auc'].append(val_auc)

    # Check for improvement
    if val_auc > best_val_auc:
        best_val_auc = val_auc
        best_model_state = copy.deepcopy(model.state_dict()) # Save best weights
        patience_counter = 0 # Reset timer
        print(f"Epoch {epoch:03d} | Loss: {loss:.4f} | Val AUC: {val_auc:.4f} (New Best!)")
    else:
        patience_counter += 1
        print(f"Epoch {epoch:03d} | Loss: {loss:.4f} | Val AUC: {val_auc:.4f}")

    # Stop if patience runs out
    if patience_counter >= PATIENCE:
        print(f"\n🛑 Early Stopping triggered at Epoch {epoch}!")
        print(f"   Model stopped improving. The best AUC was {best_val_auc:.4f}")
        break

# LOAD BEST WEIGHTS BEFORE CONTINUING
if best_model_state is not None:
    model.load_state_dict(best_model_state)
    print("✅ Best model weights loaded.")

# ==============================================================================
# 7. VISUALIZATIONS
# ==============================================================================

# --- A. Training Curves ---
plt.figure(figsize=(12, 5))

# Plot Loss
plt.subplot(1, 2, 1)
plt.plot(history['loss'], label='Training Loss', color='red')
plt.title('BPR Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss (Lower is Better)')
plt.grid(True, alpha=0.3)
plt.legend()

# Plot AUC
plt.subplot(1, 2, 2)
plt.plot(history['val_auc'], label='Validation AUC', color='blue')
plt.title('Validation AUC over Epochs')
plt.xlabel('Epoch')
plt.ylabel('AUC (Higher is Better)')
plt.grid(True, alpha=0.3)
plt.legend()

plt.tight_layout()
plt.show()

# --- B. Score Distribution (Why BPR works) ---
# We want to see Positive scores pushed to the right, Negatives to the left
_, pos_scores, neg_scores = test_step(test_data)
pos_scores = pos_scores.cpu().numpy()
neg_scores = neg_scores.cpu().numpy()

plt.figure(figsize=(10, 6))
sns.histplot(pos_scores, color='green', alpha=0.5, label='Real Connections (Pos)', kde=True)
sns.histplot(neg_scores, color='red', alpha=0.5, label='Random Pairs (Neg)', kde=True)
plt.title('Distribution of Prediction Scores (Test Set)')
plt.xlabel('Similarity Score (Cosine)')
plt.ylabel('Frequency')
plt.legend()
plt.show()

# --- C. t-SNE Embedding Space (The "Map") ---
print("Generating t-SNE Visualization (this may take a moment)...")

# Get final user embeddings
model.eval()
with torch.no_grad():
    all_out = model(data.x_dict, data.edge_index_dict)
    user_emb = all_out['user'].cpu().numpy()

# Reduce to 2D for plotting
# We take a sample of 2000 users to keep it fast and readable
sample_size = 2000
if len(df) < sample_size: sample_size = len(df) # Handle small datasets

indices = np.random.choice(len(df), sample_size, replace=False)
user_emb_sample = user_emb[indices]
majors_sample = df.iloc[indices]['Major'].values

tsne = TSNE(n_components=2, perplexity=30, random_state=42)
z_tsne = tsne.fit_transform(user_emb_sample)

plt.figure(figsize=(12, 10))
# Plot scatter, coloring by Major to see if clusters formed
sns.scatterplot(x=z_tsne[:,0], y=z_tsne[:,1], hue=majors_sample, palette='tab10', s=60, alpha=0.7)
plt.title('User Embeddings Cluster Map (t-SNE)')
# Move legend outside
plt.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
plt.show()

# ==============================================================================
# 8. THE FINAL TEST: SEE THE RECOMMENDATIONS
# ==============================================================================
print("\n[Step 5/5] Generating Final Friend Recommendations...")

# 1. Get the learned "Graph-Aware" Embeddings
model.eval()
with torch.no_grad():
    # We pass the whole graph through the model one last time
    out_dict = model(data.x_dict, data.edge_index_dict)
    # We only care about the USER vectors for finding friends
    user_embeddings = out_dict['user'].cpu().numpy()

# 2. Setup the Search Engine (KNN)
# We use Cosine Similarity because we normalized the vectors in the model
knn = NearestNeighbors(n_neighbors=6, metric='cosine')
knn.fit(user_embeddings)

# 3. Helper Function to Print Results
def show_recommendations(user_idx):
    distances, indices = knn.kneighbors([user_embeddings[user_idx]])

    target_user = df.iloc[user_idx]
    print(f"\n============================================================")
    print(f"👤  FOCUS USER: {target_user['Name']}")
    print(f"    Major: {target_user['Major']} | Age: {target_user['Age']}")
    print(f"    Bio:   {target_user['Unique Quality']}...")
    print(f"    Likes: {target_user['Hobbies']}")
    print(f"============================================================")

    print("⬇️  TOP 5 RECOMMENDED FRIENDS  ⬇️")

    for rank, neighbor_idx in enumerate(indices[0][1:]):
        friend = df.iloc[neighbor_idx]
        similarity_score = (1 - distances[0][rank+1]) * 100

        print(f"\n{rank+1}. {friend['Name']} (Match: {similarity_score:.1f}%)")
        print(f"   🎂 Age:   {friend['Age']} | Major: {friend['Major']}") # <--- ADDED AGE HERE
        print(f"   🧩 Likes: {friend['Hobbies']}")
        print(f"   📝 Bio:   {friend['Unique Quality']}")

# --- RUN DEMO FOR FIRST 3 USERS ---
for i in range(3):
    show_recommendations(i)

##ReRanking ##

# ==============================================================================
# 8. THE FINAL TEST: SEE THE RECOMMENDATIONS
# ==============================================================================
print("\n[Step 5/5] Generating Final Friend Recommendations...")

# 1. Get the learned "Graph-Aware" Embeddings
model.eval()
with torch.no_grad():
    # We pass the whole graph through the model one last time
    out_dict = model(data.x_dict, data.edge_index_dict)
    # We only care about the USER vectors for finding friends
    user_embeddings = out_dict['user'].cpu().numpy()

# 2. Setup the Search Engine (KNN)
# We use Cosine Similarity because we normalized the vectors in the model
knn = NearestNeighbors(n_neighbors=6, metric='cosine')
knn.fit(user_embeddings)

# 3. Helper Function to Print Results
def show_recommendations(user_idx):
    # 1. Get more candidates (e.g., Top 50) instead of just 5
    # We broaden the search so we have room to filter/sort
    distances, indices = knn.kneighbors([user_embeddings[user_idx]], n_neighbors=50)

    target_user = df.iloc[user_idx]
    target_age = target_user['Age']

    print(f"\n============================================================")
    print(f"👤  FOCUS USER: {target_user['Name']}")
    print(f"    Major: {target_user['Major']} | Age: {target_age}")
    print(f"    Likes: {target_user['Hobbies']}")
    print(f"============================================================")

    print("⬇️  TOP 5 RECOMMENDED FRIENDS (Age Adjusted) ⬇️")

    candidates = []

    # 2. Loop through candidates and calculate a "Hybrid Score"
    for rank, neighbor_idx in enumerate(indices[0][1:]): # Skip self
        friend = df.iloc[neighbor_idx]
        friend_age = friend['Age']

        # Raw Similarity from GNN (0.0 to 1.0)
        raw_score = (1 - distances[0][rank+1])

        # Calculate Age Penalty
        # Rule: Subtract 1.5% from score for every year of difference
        age_diff = abs(target_age - friend_age)
        age_penalty = age_diff * 0.015

        # Final Adjusted Score
        final_score = raw_score - age_penalty

        candidates.append({
            'idx': neighbor_idx,
            'name': friend['Name'],
            'age': friend_age,
            'major': friend['Major'],
            'hobbies': friend['Hobbies'],
            'bio': friend['Unique Quality'],
            'score': final_score * 100 # Convert to percentage
        })

    # 3. Sort by the NEW Final Score
    candidates.sort(key=lambda x: x['score'], reverse=True)

    # 4. Print top 5
    for i, person in enumerate(candidates[:5]):
        print(f"\n{i+1}. {person['name']} (Score: {person['score']:.1f}%)")
        print(f"   🎂 Age:   {person['age']} (Gap: {abs(target_age - person['age'])} yrs)")
        print(f"   🎓 Major: {person['major']}")
        print(f"   🧩 Likes: {person['hobbies']}")

for i in range(3):
    show_recommendations(i)

# ==============================================================================
# UPDATED STEP 9: SAVE EVERYTHING FOR THE API
# ==============================================================================
import pickle
import os

save_path = "/content/drive/My Drive/SocialGraphModel"
os.makedirs(save_path, exist_ok=True)

# 1. Save Model Weights (Same as before)
torch.save(model.state_dict(), os.path.join(save_path, "gnn_model.pth"))

# 2. Save Inference Vectors (Same as before)
np.save(os.path.join(save_path, "user_embeddings.npy"), user_embeddings)

# 3. Create ID Mapping (Crucial for API)
# Maps Real ID (15001) -> Graph Index (0)
id_map = {row['student_id']: i for i, row in df.iterrows()}

# 4. Save Artifacts + DataFrame + ID Map
artifacts = {
    'scaler': scaler,
    'knn': knn,
    'major_map': major_map,
    'hobby_map': hobby_map,
    'year_map': year_map,
    'metadata': data.metadata(),
    'id_map': id_map,        # <--- NEW: To find users by real ID
    'df': df                 # <--- NEW: To show names/bios instantly
}

with open(os.path.join(save_path, "artifacts.pkl"), "wb") as f:
    pickle.dump(artifacts, f)

print("✅ Saved Model, Vectors, ID Map, and Profile Data!")

