# -*- coding: utf-8 -*-
"""StudyBuddyFinder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19bcf1NkDLXDERcs2Pthoa0PGo_Y8c3UE
"""

import pandas as pd

df = pd.read_csv('profiles_updated.csv')

print("First 5 rows of the dataset:")
print(df.head())
print("\nDataset Information:")
df.info()

"""[link text](https://)# Augmenting Dataset with Courses, Course Schedule of Students

"""



!pip install -q torch-geometric sentence-transformers

import os
import ast
import torch
import numpy as np
import pandas as pd
import torch.nn.functional as F
from torch_geometric.data import HeteroData
from torch_geometric.nn import SAGEConv, to_hetero
import torch_geometric.transforms as T
from sentence_transformers import SentenceTransformer
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import NearestNeighbors

# ==============================================================================
# 1. SETUP & CONFIGURATION
# ==============================================================================
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# ==============================================================================
# 2. DATA LOADING & FEATURE ENGINEERING
# ==============================================================================
print("\n[Step 1/5] Loading and Processing Data...")

# --- A. Text Embeddings ---
# UPDATED FILENAME HERE
embeddings_file_path = '/content/drive/MyDrive/study_buddy_user_embeddings.npy'

if os.path.exists(embeddings_file_path):
    print("   -> Loading cached MPNet embeddings from Drive...")
    text_embeddings = np.load(embeddings_file_path)
else:
    print("   -> Generating MPNet embeddings...")
    df['full_text'] = df['Unique Quality'] + ". " + df['Story']
    encoder = SentenceTransformer('all-mpnet-base-v2')
    text_embeddings = encoder.encode(df['full_text'].tolist(), show_progress_bar=True)
    np.save(embeddings_file_path, text_embeddings)

year_map = {'Freshman': 1, 'Sophomore': 2, 'Junior': 3, 'Senior': 4, 'Graduate': 5, 'PhD': 6}
df['Year_Num'] = df['Year'].map(year_map).fillna(1)

scaler = StandardScaler()
numerical_feats = scaler.fit_transform(df[['Age', 'GPA', 'Year_Num']].values)

le_sex = LabelEncoder()
sex_feats = le_sex.fit_transform(df['Sex']).reshape(-1, 1)
user_features = np.hstack([text_embeddings, numerical_feats, sex_feats])
user_x = torch.tensor(user_features, dtype=torch.float)
print(f"   -> User Feature Matrix Shape: {user_x.shape}")

print("\n[Step 2/5] Building Heterogeneous Graph...")

data = HeteroData()
data['user'].x = user_x
data['user'].num_nodes = len(df)
unique_majors = df['Major'].unique()
major_map = {m: i for i, m in enumerate(unique_majors)}
data['major'].num_nodes = len(unique_majors)
data['major'].x = torch.eye(len(unique_majors))
hobby_set = set()
user_hobby_pairs = []
for idx, row in df.iterrows():
    try:
        h_list = ast.literal_eval(row['Hobbies']) if isinstance(row['Hobbies'], str) else row['Hobbies']
        for h in h_list:
            h_clean = h.strip().lower()
            hobby_set.add(h_clean)
            user_hobby_pairs.append((idx, h_clean))
    except:
        continue

unique_hobbies = sorted(list(hobby_set))
hobby_map = {h: i for i, h in enumerate(unique_hobbies)}
data['hobby'].num_nodes = len(unique_hobbies)
data['hobby'].x = torch.eye(len(unique_hobbies))
course_set = set()
user_course_pairs = []
for idx, row in df.iterrows():
    try:
        c_list = ast.literal_eval(row['Courses']) if isinstance(row['Courses'], str) else row['Courses']
        for c in c_list:
            c_clean = c.strip()
            course_set.add(c_clean)
            user_course_pairs.append((idx, c_clean))
    except:
        continue

unique_courses = sorted(list(course_set))
course_map = {c: i for i, c in enumerate(unique_courses)}
data['course'].num_nodes = len(unique_courses)
data['course'].x = torch.eye(len(unique_courses))
slot_set = set()
user_slot_pairs = []
for idx, row in df.iterrows():
    try:
        s_list = ast.literal_eval(row['Free_Slots']) if isinstance(row['Free_Slots'], str) else row['Free_Slots']
        for s in s_list:
            s_clean = s.strip()
            slot_set.add(s_clean)
            user_slot_pairs.append((idx, s_clean))
    except:
        continue

unique_slots = sorted(list(slot_set))
slot_map = {s: i for i, s in enumerate(unique_slots)}
data['timeslot'].num_nodes = len(unique_slots)
data['timeslot'].x = torch.eye(len(unique_slots))

print(f"   -> Nodes Created: {data.num_nodes} total nodes")
u_indices = []
m_indices = []
for idx, row in df.iterrows():
    if row['Major'] in major_map:
        u_indices.append(idx)
        m_indices.append(major_map[row['Major']])
data['user', 'studies', 'major'].edge_index = torch.tensor([u_indices, m_indices], dtype=torch.long)
u_h_src = []
h_dst = []
for u_idx, h_name in user_hobby_pairs:
    if h_name in hobby_map:
        u_h_src.append(u_idx)
        h_dst.append(hobby_map[h_name])
data['user', 'likes', 'hobby'].edge_index = torch.tensor([u_h_src, h_dst], dtype=torch.long)
u_c_src = []
c_dst = []
for u_idx, c_name in user_course_pairs:
    if c_name in course_map:
        u_c_src.append(u_idx)
        c_dst.append(course_map[c_name])
data['user', 'enrolled_in', 'course'].edge_index = torch.tensor([u_c_src, c_dst], dtype=torch.long)
s_dst = []
for u_idx, s_name in user_slot_pairs:
    if s_name in slot_map:
        u_s_src.append(u_idx)
        s_dst.append(slot_map[s_name])
data['user', 'is_free_at', 'timeslot'].edge_index = torch.tensor([u_s_src, s_dst], dtype=torch.long)
data = T.ToUndirected()(data)

# Move to GPU/CPU
data = data.to(device)
print(f"   -> Graph Ready: {data}")

from google.colab import drive
drive.mount('/content/drive')

import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.transforms import RandomLinkSplit


print("\n[Step 3/5] Initializing Model...")

class SocialGNN(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels):
        super().__init__()
        self.conv1 = SAGEConv((-1, -1), hidden_channels)
        self.bn = nn.BatchNorm1d(hidden_channels)
        self.conv2 = SAGEConv((-1, -1), out_channels)
        self.dropout = nn.Dropout(p=0.2)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = self.bn(x)
        x = F.relu(x)
        x = self.dropout(x)
        x = self.conv2(x, edge_index)
        return F.normalize(x, p=2, dim=-1)


model = SocialGNN(hidden_channels=256, out_channels=64)
model = to_hetero(model, data.metadata(), aggr='sum').to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.0005, weight_decay=1e-4)
transform = RandomLinkSplit(
    num_val=0.1,
    num_test=0.1,
    is_undirected=True,
    edge_types=[('user', 'likes', 'hobby')],
    add_negative_train_samples=False
)
train_data, val_data, test_data = transform(data)
print("   -> Data Split Complete.")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_auc_score

history = {'loss': [], 'val_auc': [], 'val_hit_rate': []}

def train_step():
    model.train()
    optimizer.zero_grad()

    out = model(train_data.x_dict, train_data.edge_index_dict)
    edge_type = ('user', 'likes', 'hobby')
    src, dst = train_data[edge_type].edge_label_index
    pos_score = (out['user'][src] * out['hobby'][dst]).sum(dim=-1)
    neg_dst = torch.randint(0, data['hobby'].num_nodes, (len(src),), device=device)
    neg_score = (out['user'][src] * out['hobby'][neg_dst]).sum(dim=-1)
    loss = -torch.log(torch.sigmoid(pos_score - neg_score) + 1e-15).mean()

    loss.backward()
    optimizer.step()
    return loss.item()

@torch.no_grad()
def test_step(data_split):
    model.eval()
    out = model(data_split.x_dict, data_split.edge_index_dict)

    edge_type = ('user', 'likes', 'hobby')
    src, dst = data_split[edge_type].edge_label_index
    pos_score = (out['user'][src] * out['hobby'][dst]).sum(dim=-1)
    neg_dst = torch.randint(0, data['hobby'].num_nodes, (len(src),), device=device)
    neg_score = (out['user'][src] * out['hobby'][neg_dst]).sum(dim=-1)

    y_true = torch.cat([torch.ones(pos_score.size(0)), torch.zeros(neg_score.size(0))]).cpu().numpy()
    y_score = torch.cat([pos_score, neg_score]).sigmoid().cpu().numpy()
    auc = roc_auc_score(y_true, y_score)
    k = 10
    hits = 0
    total = 0
    sample_indices = torch.randperm(len(src))[:500]

    user_embeds = out['user']
    hobby_embeds = out['hobby']

    for idx in sample_indices:
        u_idx = src[idx]
        real_hobby = dst[idx]
        all_scores = torch.matmul(user_embeds[u_idx], hobby_embeds.t())
        _, top_indices = torch.topk(all_scores, k)

        if real_hobby in top_indices:
            hits += 1
        total += 1

    hit_rate = hits / total

    return auc, hit_rate

print("\n[Step 4/5] Training...")
MAX_EPOCHS = 60
PATIENCE = 12
best_val_auc = 0
patience_counter = 0

for epoch in range(1, MAX_EPOCHS + 1):
    loss = train_step()
    val_auc, val_hit = test_step(val_data)

    history['loss'].append(loss)
    history['val_auc'].append(val_auc)
    history['val_hit_rate'].append(val_hit)

    if val_auc > best_val_auc:
        best_val_auc = val_auc
        patience_counter = 0
        print(f"Epoch {epoch:02d} | Loss: {loss:.4f} | AUC: {val_auc:.4f} | Hit@10: {val_hit:.2f} *")
    else:
        patience_counter += 1
        if epoch % 10 == 0:
            print(f"Epoch {epoch:02d} | Loss: {loss:.4f} | AUC: {val_auc:.4f} | Hit@10: {val_hit:.2f}")

    if patience_counter > PATIENCE:
        print("Early stopping!")
        break

print(f"Training Finished. Best AUC: {best_val_auc:.4f}")
plt.figure(figsize=(15, 5))

# Plot 1: Loss
plt.subplot(1, 3, 1)
plt.plot(history['loss'], label='BPR Loss', color='red')
plt.title('Training Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.grid(True, alpha=0.3)

# Plot 2: AUC
plt.subplot(1, 3, 2)
plt.plot(history['val_auc'], label='Validation AUC', color='blue')
plt.title('Validation AUC')
plt.xlabel('Epoch')
plt.ylabel('AUC')
plt.grid(True, alpha=0.3)

# Plot 3: Hit Rate (The "Real World" metric)
plt.subplot(1, 3, 3)
plt.plot(history['val_hit_rate'], label='Hit Rate @ 10', color='green')
plt.title('Hit Rate (Top-10 Accuracy)')
plt.xlabel('Epoch')
plt.ylabel('Proportion')
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# ==============================================================================
# 7. GENERATE STUDY BUDDY RECOMMENDATIONS
# ==============================================================================
print("\n[Step 5/5] Generating Recommendations...")

# 1. Get Final User Embeddings
model.eval()
with torch.no_grad():
    out = model(data.x_dict, data.edge_index_dict)
    user_embeddings = out['user'].cpu().numpy()

# 2. Fit KNN
knn = NearestNeighbors(n_neighbors=10, metric='cosine')
knn.fit(user_embeddings)

# 3. Helper to find overlaps
def find_overlaps(user_idx_a, user_idx_b):
    # Get raw strings from dataframe
    courses_a = set(ast.literal_eval(df.iloc[user_idx_a]['Courses']))
    courses_b = set(ast.literal_eval(df.iloc[user_idx_b]['Courses']))

    slots_a = set(ast.literal_eval(df.iloc[user_idx_a]['Free_Slots']))
    slots_b = set(ast.literal_eval(df.iloc[user_idx_b]['Free_Slots']))

    shared_courses = list(courses_a.intersection(courses_b))
    shared_slots = list(slots_a.intersection(slots_b))

    return shared_courses, shared_slots

# 4. Show Results
def recommend_study_buddy(user_idx):
    target_user = df.iloc[user_idx]
    print(f"\n📘 FOCUS STUDENT: {target_user['Name']}")
    print(f"   Major: {target_user['Major']}")
    print(f"   Courses: {target_user['Courses']}")
    print("-" * 60)

    distances, indices = knn.kneighbors([user_embeddings[user_idx]])

    found_count = 0
    for rank, neighbor_idx in enumerate(indices[0][1:]):
        friend = df.iloc[neighbor_idx]

        # Calculate overlaps to explain the match
        shared_courses, shared_slots = find_overlaps(user_idx, neighbor_idx)

        # We prefer matches that share at least 1 course OR have good time overlap
        # The GNN prioritizes this automatically, but let's visualize it.

        score = (1 - distances[0][rank+1]) * 100

        print(f"{rank+1}. {friend['Name']} (Match Score: {score:.1f}%)")
        print(f"   🎓 Major: {friend['Major']}")

        if shared_courses:
            print(f"   📚 SHARED CLASS: {', '.join(shared_courses)}")
        else:
            print(f"   📚 Classes: {friend['Courses']}")

        if len(shared_slots) > 0:
            print(f"   ⏰ Matching Free Time: {len(shared_slots)} blocks (e.g., {shared_slots[0]})")
        else:
            print(f"   ⚠️ No schedule overlap")

        print("-" * 30)
        found_count += 1
        if found_count >= 5: break

# Run for the first student
recommend_study_buddy(0)
recommend_study_buddy(1)

import ast

# ==============================================================================
# UPDATED RECOMMENDATION ENGINE (LOGIC-BASED SORTING)
# ==============================================================================

def get_study_buddy_recommendations(user_idx):
    target_user = df.iloc[user_idx]

    # 1. Parse Target User Data safely
    try:
        my_courses = set(ast.literal_eval(target_user['Courses'])) if isinstance(target_user['Courses'], str) else set(target_user['Courses'])
        my_slots = set(ast.literal_eval(target_user['Free_Slots'])) if isinstance(target_user['Free_Slots'], str) else set(target_user['Free_Slots'])
    except:
        my_courses, my_slots = set(), set()

    print(f"\n📘 FOCUS STUDENT: {target_user['Name']}")
    print(f"   Major: {target_user['Major']}")
    print(f"   Courses: {list(my_courses)}")
    print("=" * 70)

    # 2. Get Top 50 Candidates from GNN (Broad Search)
    # We fetch 50 so we have enough people to re-rank based on classes
    distances, indices = knn.kneighbors([user_embeddings[user_idx]], n_neighbors=50)

    candidates = []

    # 3. Analyze Candidates
    for rank, neighbor_idx in enumerate(indices[0][1:]): # Skip self
        friend = df.iloc[neighbor_idx]

        # Parse Friend Data
        try:
            friend_courses = set(ast.literal_eval(friend['Courses'])) if isinstance(friend['Courses'], str) else set(friend['Courses'])
            friend_slots = set(ast.literal_eval(friend['Free_Slots'])) if isinstance(friend['Free_Slots'], str) else set(friend['Free_Slots'])
        except:
            continue

        # --- CALCULATE METRICS ---
        shared_courses = list(my_courses.intersection(friend_courses))
        shared_slots = list(my_slots.intersection(friend_slots))

        gnn_similarity = (1 - distances[0][rank+1]) # 0.0 to 1.0

        # --- THE "BUSINESS LOGIC" SCORING FORMULA ---
        # Priority 1: SHARED CLASS (Massive Boost)
        class_score = len(shared_courses) * 10.0

        # Priority 2: TIME OVERLAP (Moderate Boost)
        # We cap this so 100 free blocks don't override a missing class
        time_score = min(len(shared_slots) * 0.05, 3.0)

        # Priority 3: PROFILE SIMILARITY (Tie Breaker)
        profile_score = gnn_similarity * 2.0

        final_score = class_score + time_score + profile_score

        candidates.append({
            'name': friend['Name'],
            'major': friend['Major'],
            'shared_courses': shared_courses,
            'friend_courses': list(friend_courses),
            'shared_slots_count': len(shared_slots),
            'example_slot': shared_slots[0] if shared_slots else None,
            'final_score': final_score,
            'gnn_match': gnn_similarity * 100
        })

    # 4. Sort by Final Score (Descending)
    candidates.sort(key=lambda x: x['final_score'], reverse=True)

    # 5. Display Top 5
    for i, person in enumerate(candidates[:5]):
        print(f"{i+1}. {person['name']} (Score: {person['final_score']:.2f})")
        print(f"   🎓 Major: {person['major']}")

        # Dynamic Printing based on what matched
        if person['shared_courses']:
            print(f"   ✅ SHARED CLASS: {', '.join(person['shared_courses'])}")
        else:
            # If no shared class, show what they DO take
            print(f"   📚 Classes: {person['friend_courses'][:2]}...")

        print(f"   ⏰ Free Time Match: {person['shared_slots_count']} blocks (e.g., {person['example_slot']})")
        print(f"   🧠 Profile Match: {person['gnn_match']:.1f}%")
        print("-" * 30)

# Run it
get_study_buddy_recommendations(0)

import os
import ast
import copy
import torch
import numpy as np
import pandas as pd
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.data import HeteroData
from torch_geometric.nn import SAGEConv, to_hetero
import torch_geometric.transforms as T
from torch_geometric.transforms import RandomLinkSplit
from sentence_transformers import SentenceTransformer
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import roc_auc_score

# ==============================================================================
# 1. SETUP & CONFIGURATION
# ==============================================================================
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"✅ Using device: {device}")

# ==============================================================================
# 2. DATA LOADING & FEATURE ENGINEERING
# ==============================================================================
print("\n[Step 1/6] Loading and Processing Data...")

# Load your CSV (Must contain 'Courses' and 'Free_Slots' columns)
try:
    df = pd.read_csv("profiles_updated.csv")
except FileNotFoundError:
    raise FileNotFoundError("❌ 'profiles_processed.csv' not found. Please upload it.")

# --- A. Text Embeddings ---
# We use a specific filename for the study buddy model
embeddings_file_path = '/content/drive/MyDrive/study_buddy_user_embeddings.npy'

if os.path.exists(embeddings_file_path):
    print("   -> Loading cached MPNet embeddings...")
    text_embeddings = np.load(embeddings_file_path)
else:
    print("   -> Generating MPNet embeddings (this takes time)...")
    # Combine relevant text
    df['full_text'] = df['Unique Quality'] + ". " + df['Story']

    encoder = SentenceTransformer('all-mpnet-base-v2')
    text_embeddings = encoder.encode(df['full_text'].tolist(), show_progress_bar=True)

    # Save if using Drive
    if os.path.isdir(os.path.dirname(embeddings_file_path)):
        np.save(embeddings_file_path, text_embeddings)

# --- B. Numerical Features ---
year_map = {'Freshman': 1, 'Sophomore': 2, 'Junior': 3, 'Senior': 4, 'Graduate': 5, 'PhD': 6}
df['Year_Num'] = df['Year'].map(year_map).fillna(1)

scaler = StandardScaler()
numerical_feats = scaler.fit_transform(df[['Age', 'GPA', 'Year_Num']].values)

# --- C. Categorical Features ---
le_sex = LabelEncoder()
sex_feats = le_sex.fit_transform(df['Sex']).reshape(-1, 1)

# --- D. Combine All User Features ---
user_features = np.hstack([text_embeddings, numerical_feats, sex_feats])
user_x = torch.tensor(user_features, dtype=torch.float)
print(f"   -> User Feature Matrix Shape: {user_x.shape}")

# ==============================================================================
# 3. GRAPH CONSTRUCTION (Social + Logistical)
# ==============================================================================
print("\n[Step 2/6] Building Heterogeneous Graph...")

data = HeteroData()

# --- A. Create Nodes ---

# 1. User
data['user'].x = user_x
data['user'].num_nodes = len(df)

# Helper to process list columns safely
def get_node_map_and_pairs(column_name):
    unique_set = set()
    pairs = []
    for idx, row in df.iterrows():
        try:
            # Handle stringified lists from CSV
            items = ast.literal_eval(row[column_name]) if isinstance(row[column_name], str) else row[column_name]
            for item in items:
                clean_item = item.strip()
                unique_set.add(clean_item)
                pairs.append((idx, clean_item))
        except:
            continue
    sorted_items = sorted(list(unique_set))
    item_map = {item: i for i, item in enumerate(sorted_items)}
    return sorted_items, item_map, pairs

# 2. Major (One-Hot)
unique_majors = df['Major'].unique()
major_map = {m: i for i, m in enumerate(unique_majors)}
data['major'].num_nodes = len(unique_majors)
data['major'].x = torch.eye(len(unique_majors))

# 3. Hobby (One-Hot)
hobbies, hobby_map, user_hobby_pairs = get_node_map_and_pairs('Hobbies')
data['hobby'].num_nodes = len(hobbies)
data['hobby'].x = torch.eye(len(hobbies))

# 4. Course (One-Hot) - CRITICAL for Study Buddy
courses, course_map, user_course_pairs = get_node_map_and_pairs('Courses')
data['course'].num_nodes = len(courses)
data['course'].x = torch.eye(len(courses))

# 5. TimeSlot (One-Hot) - CRITICAL for Logistics
slots, slot_map, user_slot_pairs = get_node_map_and_pairs('Free_Slots')
data['timeslot'].num_nodes = len(slots)
data['timeslot'].x = torch.eye(len(slots))

print(f"   -> Graph Stats: {data.num_nodes} Nodes (Users, Majors, Hobbies, Courses, Slots)")

# --- B. Create Edges ---

# User -> Major
u_indices = [i for i, row in df.iterrows() if row['Major'] in major_map]
m_indices = [major_map[row['Major']] for i, row in df.iterrows() if row['Major'] in major_map]
data['user', 'studies', 'major'].edge_index = torch.tensor([u_indices, m_indices], dtype=torch.long)

# Helper to build edge tensors
def build_edge_tensor(pairs, target_map):
    src, dst = [], []
    for u_idx, item in pairs:
        if item in target_map:
            src.append(u_idx)
            dst.append(target_map[item])
    return torch.tensor([src, dst], dtype=torch.long)

data['user', 'likes', 'hobby'].edge_index = build_edge_tensor(user_hobby_pairs, hobby_map)
data['user', 'enrolled_in', 'course'].edge_index = build_edge_tensor(user_course_pairs, course_map)
data['user', 'is_free_at', 'timeslot'].edge_index = build_edge_tensor(user_slot_pairs, slot_map)

# --- C. Reverse Edges ---
data = T.ToUndirected()(data)
data = data.to(device)
print(f"   -> Graph Ready: {data}")

# ==============================================================================
# 4. MODEL DEFINITION
# ==============================================================================
print("\n[Step 3/6] Initializing AI Model...")

class SocialGNN(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels):
        super().__init__()
        self.conv1 = SAGEConv((-1, -1), hidden_channels)
        self.bn = nn.BatchNorm1d(hidden_channels)
        self.conv2 = SAGEConv((-1, -1), out_channels)
        self.dropout = nn.Dropout(p=0.2)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = self.bn(x)
        x = F.relu(x)
        x = self.dropout(x)
        x = self.conv2(x, edge_index)
        return F.normalize(x, p=2, dim=-1)

model = SocialGNN(hidden_channels=256, out_channels=64)
model = to_hetero(model, data.metadata(), aggr='sum').to(device)

# "Pro" settings: Lower LR and Weight Decay for stable convergence
optimizer = torch.optim.Adam(model.parameters(), lr=0.0005, weight_decay=1e-4)

# ==============================================================================
# 5. DATA SPLIT (MULTI-OBJECTIVE)
# ==============================================================================
# We split edges for BOTH Courses and Hobbies so we can calculate loss for both
transform = RandomLinkSplit(
    num_val=0.1,
    num_test=0.1,
    is_undirected=True,
    edge_types=[('user', 'likes', 'hobby'), ('user', 'enrolled_in', 'course')],
    add_negative_train_samples=False
)
train_data, val_data, test_data = transform(data)

# ==============================================================================
# 6. TRAINING LOOP (WEIGHTED LOSS)
# ==============================================================================
print("\n[Step 4/6] Training with Weighted Objectives (Courses > Hobbies)...")

def train_step():
    model.train()
    optimizer.zero_grad()
    out = model(train_data.x_dict, train_data.edge_index_dict)

    # --- Loss 1: Hobbies (Social Factor) ---
    src_h, dst_h = train_data['user', 'likes', 'hobby'].edge_label_index
    pos_h = (out['user'][src_h] * out['hobby'][dst_h]).sum(dim=-1)
    # Negative samples
    neg_dst_h = torch.randint(0, data['hobby'].num_nodes, (len(src_h),), device=device)
    neg_h = (out['user'][src_h] * out['hobby'][neg_dst_h]).sum(dim=-1)
    loss_hobby = -torch.log(torch.sigmoid(pos_h - neg_h) + 1e-15).mean()

    # --- Loss 2: Courses (Study Factor) - WEIGHTED HIGHER ---
    src_c, dst_c = train_data['user', 'enrolled_in', 'course'].edge_label_index
    pos_c = (out['user'][src_c] * out['course'][dst_c]).sum(dim=-1)
    # Negative samples
    neg_dst_c = torch.randint(0, data['course'].num_nodes, (len(src_c),), device=device)
    neg_c = (out['user'][src_c] * out['course'][neg_dst_c]).sum(dim=-1)
    loss_course = -torch.log(torch.sigmoid(pos_c - neg_c) + 1e-15).mean()

    # --- Total Weighted Loss ---
    # 5.0 multiplier forces model to prioritize Course overlap
    total_loss = loss_hobby + (5.0 * loss_course)

    total_loss.backward()
    optimizer.step()
    return total_loss.item()

@torch.no_grad()
def test_step(data_split):
    model.eval()
    out = model(data_split.x_dict, data_split.edge_index_dict)

    # Evaluate on Course prediction accuracy (The priority)
    src, dst = data_split['user', 'enrolled_in', 'course'].edge_label_index
    pos = (out['user'][src] * out['course'][dst]).sum(dim=-1)
    neg_dst = torch.randint(0, data['course'].num_nodes, (len(src),), device=device)
    neg = (out['user'][src] * out['course'][neg_dst]).sum(dim=-1)

    y_true = torch.cat([torch.ones(pos.size(0)), torch.zeros(neg.size(0))]).cpu().numpy()
    y_score = torch.cat([pos, neg]).sigmoid().cpu().numpy()
    return roc_auc_score(y_true, y_score)

# Run Training
MAX_EPOCHS = 60
best_val_auc = 0
patience_counter = 0

for epoch in range(1, MAX_EPOCHS + 1):
    loss = train_step()
    val_auc = test_step(val_data)

    if val_auc > best_val_auc:
        best_val_auc = val_auc
        patience_counter = 0
        print(f"Epoch {epoch:02d} | Loss: {loss:.4f} | Course AUC: {val_auc:.4f} *")
    else:
        patience_counter += 1
        if epoch % 10 == 0:
            print(f"Epoch {epoch:02d} | Loss: {loss:.4f} | Course AUC: {val_auc:.4f}")

    if patience_counter > 15:
        print("🛑 Early stopping triggered.")
        break

# ==============================================================================
# 7. RECOMMENDATION ENGINE (Hybrid Logic)
# ==============================================================================
print("\n[Step 5/6] Generating Logic-Based Recommendations...")

# 1. Get Final Embeddings
model.eval()
with torch.no_grad():
    out = model(data.x_dict, data.edge_index_dict)
    user_embeddings = out['user'].cpu().numpy()

# 2. Fit KNN (Retrieval Layer)
knn = NearestNeighbors(n_neighbors=50, metric='cosine')
knn.fit(user_embeddings)

# 3. Define Recommendation Function
def recommend_study_buddy(user_idx):
    target_user = df.iloc[user_idx]

    # Safe Parsing
    try:
        my_courses = set(ast.literal_eval(target_user['Courses'])) if isinstance(target_user['Courses'], str) else set(target_user['Courses'])
        my_slots = set(ast.literal_eval(target_user['Free_Slots'])) if isinstance(target_user['Free_Slots'], str) else set(target_user['Free_Slots'])
    except:
        my_courses, my_slots = set(), set()

    print(f"\n📘 FOCUS STUDENT: {target_user['Name']}")
    print(f"   Major: {target_user['Major']}")
    print(f"   Courses: {list(my_courses)}")
    print("=" * 70)

    # A. Retrieve Top 50 Candidates (AI Layer)
    distances, indices = knn.kneighbors([user_embeddings[user_idx]])

    candidates = []

    # B. Rank Candidates (Logic Layer)
    for rank, neighbor_idx in enumerate(indices[0][1:]): # Skip self
        friend = df.iloc[neighbor_idx]

        try:
            friend_courses = set(ast.literal_eval(friend['Courses'])) if isinstance(friend['Courses'], str) else set(friend['Courses'])
            friend_slots = set(ast.literal_eval(friend['Free_Slots'])) if isinstance(friend['Free_Slots'], str) else set(friend['Free_Slots'])
        except:
            continue

        # Overlaps
        shared_courses = list(my_courses.intersection(friend_courses))
        shared_slots = list(my_slots.intersection(friend_slots))

        gnn_score = (1 - distances[0][rank+1]) # 0 to 1

        # --- THE STUDY BUDDY FORMULA ---
        # 1. Shared Class = +10.0 points
        # 2. Shared Time = +0.05 points (Capped at 3.0)
        # 3. AI Similarity = +2.0 points
        final_score = (len(shared_courses) * 10.0) + \
                      (min(len(shared_slots) * 0.05, 3.0)) + \
                      (gnn_score * 2.0)

        candidates.append({
            'name': friend['Name'],
            'major': friend['Major'],
            'shared_courses': shared_courses,
            'shared_slots_count': len(shared_slots),
            'example_slot': shared_slots[0] if shared_slots else None,
            'final_score': final_score,
            'gnn_match': gnn_score * 100
        })

    # C. Sort and Display
    candidates.sort(key=lambda x: x['final_score'], reverse=True)

    for i, person in enumerate(candidates[:5]):
        print(f"{i+1}. {person['name']} (Score: {person['final_score']:.2f})")
        print(f"   🎓 Major: {person['major']}")

        if person['shared_courses']:
            print(f"   ✅ SHARED CLASS: {', '.join(person['shared_courses'])}")
        else:
            print(f"   ❌ No shared classes")

        print(f"   ⏰ Free Time Match: {person['shared_slots_count']} blocks (e.g., {person['example_slot']})")
        print(f"   🧠 Profile Match: {person['gnn_match']:.1f}%")
        print("-" * 30)

# ==============================================================================
# 8. RUN DEMO
# ==============================================================================
# Run for the first 3 students
for i in range(3):
    recommend_study_buddy(i)

import pickle
import os
import torch
import numpy as np

# ==============================================================================
# 9. SAVE EVERYTHING FOR THE API
# ==============================================================================
print("\n[Step 6/6] Saving System for Production...")

# 1. Define Path (Google Drive)
save_path = '/content/drive/MyDrive/StudyBuddyModel_v1'
os.makedirs(save_path, exist_ok=True)

# 2. Save the Trained Model Weights
# We only save the weights (state_dict), not the whole class, for safety/size
torch.save(model.state_dict(), os.path.join(save_path, "gnn_state_dict.pth"))
print(f"✅ Model weights saved to: {save_path}/gnn_state_dict.pth")

# 3. Save the Final User Embeddings (The "Search Index")
# This allows the API to find friends instantly without running the GNN every time
model.eval()
with torch.no_grad():
    out = model(data.x_dict, data.edge_index_dict)
    final_user_vectors = out['user'].cpu().numpy()

np.save(os.path.join(save_path, "final_user_vectors.npy"), final_user_vectors)
print(f"✅ Search Index saved to: {save_path}/final_user_vectors.npy")

# 4. Save "Artifacts" (Maps, Scalers, Database)
# These are strictly required to translate "CS 411" -> ID -> Vector
artifacts = {
    'scaler': scaler,               # To scale Age/GPA for new users
    'metadata': data.metadata(),    # To rebuild the GNN architecture
    'major_map': major_map,         # Map "Biochemistry" -> ID
    'hobby_map': hobby_map,         # Map "Tennis" -> ID
    'course_map': course_map,       # Map "CS 411" -> ID
    'slot_map': slot_map,           # Map "Mon_14:00" -> ID
    'df_search': df[['Name', 'Major', 'Courses', 'Free_Slots', 'Unique Quality']] # Lightweight DB for API responses
}

with open(os.path.join(save_path, "api_artifacts.pkl"), "wb") as f:
    pickle.dump(artifacts, f)

print(f"✅ API Artifacts saved to: {save_path}/api_artifacts.pkl")
print("\n🎉 SYSTEM READY FOR DEPLOYMENT!")